### ISSUE TITLE
PHP Fatal error:  Trait 'JMac\Testing\Traits\HttpTestAssertions' not found in ...

### ISSUE THREAD

**Issue by tyler36** [laravel-shift/blueprint#100]
Just finished watching your "**Rapid Code Generation With Blueprint**" episode on Laracasts. Nice job!

Having issue with running the tests generated.
```
Trait 'JMac\Testing\Traits\HttpTestAssertions' not found in
```

You don't mention anything in the video or on the main website.
Searching through issues, you've closed 2 issues with a "install my other package" comment.

I tried installing said package: ```composer require --dev jasonmccreary/laravel-test-assertions``` and updated the TestCase.

But still getting the same error. 

Where is the "HttpTestAssertions" file you use in test generated in by Blueshift? I can not find it in this or the 'laravel-test-assertions' repo.

**Comment by jasonmccreary** [comment]
This actually has to do with the new 1.0 version of `jasonmccreary/laravel-test-assertions`. The `HttpTestAssertions` trait was renamed to `AdditionalAssertions`.

You can fix this in your code with a search and replace and I'll get a patch to Blueprint to use the new trait.

**Comment by nathane** [comment]
@tyler36 `HttpTestAssertions` was renamed to `AdditionalAssertions`. jasonmccreary/laravel-test-assertions#15

**Comment by tyler36** [comment]
Ahh ... cheers for the quick update.

**Comment by tyler36** [comment]
If blueprint relies on your other package, it might be wise to include a test to catch the rename error or even a comment in the readme. 

Anyone following the Laracast episode won't have any idea that your other package is required.

**Comment by tyler36** [comment]
Love your work 🎉 30 minutes from issue to solution!
