### ISSUE TITLE
Pivot table

### ISSUE THREAD

**Issue by coding-sunshine** [laravel-shift/blueprint#112]
I Checked PR #72 

But not able to understand how to achieve pivot table, still. Sorry if I sound dumb here but struggled a lot with this.

```
Schema::create('member_property', function (Blueprint $table) {

            $table->unsignedBigInteger('member_id')->index();
            $table->foreign('member_id')->references('id')->on('members');

            $table->unsignedBigInteger('property_id')->index();
            $table->foreign('property_id')->references('id')->on('properties');

            $table->timestamps();
        });
```

cam anyone please help?

**Comment by nathane** [comment]
Pivot tables are not supported in the current release. There is an open pull request (#104) that requires testing & review. If that's not what you're looking for, you're welcome to contribute.

**Comment by jasonmccreary** [comment]
Yes, at the moment, you'd have to create a definition for the pivot table models.

As @nathane, there is an open PR I hope to merge in the next day or two.

**Comment by jasonmccreary** [comment]
@coding-sunshine #104 was merged. You can update your constraint to `dev-master` to try this out. I'll officially include it in `1.6` tomorrow. So check it out and let us know.
