### ISSUE TITLE
PHP Fatal error:  Trait 'JMac\Testing\Traits\HttpTestAssertions' not found

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#115]
Running the generated tests will throw the above.

Now, given you know which composer package you should pull (which isn't mentioned in the docs):

`composer require --dev jasonmccreary/laravel-test-assertions`

you still get that error. The reason being that the generated tests are still referencing `HttpTestAssertions`, whereas, in the released `laravel-test-assertions` package this class has been renamed `AdditionalAssertions`.

It's even mentioned in the release notes of 1.0 of that package:

https://github.com/jasonmccreary/laravel-test-assertions/releases/tag/v1.0.0

>Please note, if you were using this package before, you will need to rename all uses of the HttpTestAssertions trait to AdditionalAssertions.

**Comment by azurinspire** [comment]
And I think that should be optional thing anyway, I don't think this kind of tool should propose to use additional libraries by default.

**Comment by jasonmccreary** [comment]
Yes, this is fixed in `master`. Just waiting to tag.

The package is _suggested_ during install by Composer. As such, it's not a requirement. You could simply remove any generated code which used it as it should only be a few assertions.

**Comment by efrontsa** [comment]
the issue still exists 😢

**Comment by jasonmccreary** [comment]
Did you install the package as suggested?
