### ISSUE TITLE
Tests Namespace Collision

### ISSUE THREAD

**Issue by diogogomeswww** [laravel-shift/blueprint#119]
First of all thank you for this!
I'm going to use it for sure and contribute to it.

1 Issue and 1 Suggestion:

- Issue:
Laravel's TestCase class has the same namespace as this package TestCase.

![image](https://user-images.githubusercontent.com/11543163/79508814-2bd01a00-8032-11ea-9b2c-3d6c44fdd638.png)

- Suggestion:
Add a model schema table with all the options/modifiers so its easy/quick to find all the available options.

**Comment by jasonmccreary** [comment]
As far as the first item, It should not be getting included in the wild. But I'll take another look within Blueprint.

Could you elaborate by what you mean on the second. I like the idea, but having trouble visualizing how it would look on the easy to find/reference bit.
