### ISSUE TITLE
Ability to create softDeletes column type

### ISSUE THREAD

**Issue by owenconti** [laravel-shift/blueprint#12]
It would be awesome to be able to indicate a model is soft deletable, which would add the trait and the `deleted_at` table column.

**Comment by jasonmccreary** [comment]
Thanks for opening this. Had a minute this morning so quickly added this functionality and tagged a [v0.4.0](https://github.com/laravel-shift/blueprint/releases/tag/0.4.0).

You can now specify a shorthand column of `softdeletes` (or `softDeletes`) in your model definitions to quickly generate a model with the `SoftDeletes` trait.

You may [review this commit](https://github.com/laravel-shift/blueprint/commit/037f5b995539102c5eaabbff8377374f9921bd28) for full details.
