### ISSUE TITLE
Use of $request->validated() when saving "validated data"

### ISSUE THREAD

**Issue by timwass** [laravel-shift/blueprint#125]
Hi, I like the project, thank you for creating it. Just one thing I noticed is you are using $request->all() in generated code like this:

`$post = Post::create($request->all());`

There are some risks using $request->all() in the create or update methods like explained in this video https://www.youtube.com/watch?v=QQS5oEOguRU. I think it is probably best to consider using validated() instead of all(), what do you think?

**Comment by Naoray** [comment]
Since Blueprint also fills out the `$fillable` property on each model it's save to use `$request->all()` in this context. Every parameter which is not defined in the `$fillable` property will be rejected and therefore not inserted into the DB.

**Comment by timwass** [comment]
True, it's easy to fix by just removing the property from `$fillable` but if I add for example a `is_admin` property via drafts.yaml to the user blueprint will automatically add it to `$fillable`.

It's not a big deal if you know about it but I'm sure many developers will not notice, I think it's better to generate code that's secure by default.

**Comment by jasonmccreary** [comment]
Blueprint aims to follow Laravel conventions and as such uses `fillable` by default.

However, I do agree that [mass assignment can be a lacking and confusing feature](https://jasonmccreary.me/articles/changes-to-streamline-laravel/) at times.

I'm going to revisit this and attempt to use `$request->validated()` when there is a known use of a `validate` statement followed by a `save` statement. That should be a happy medium.

Of course, please remember Blueprint is a tool to help you rapidly generate code. This is not necessarily consider "production ready". You should always review the generated code for your own optimizations and improvements.
