### ISSUE TITLE
[Question] Rules Translator returns 'required' by default

### ISSUE THREAD

**Issue by Naoray** [laravel-shift/blueprint#126]
Was just wondering why the `required` rule is returned by [default](https://github.com/laravel-shift/blueprint/blob/master/src/Translators/Rules.php#L12)? Probably you use it only for FormRequest creation which always needs a `required` for every column (just guessing)?

Was just wondering if there is a chance of changing the behaviour to apply for other use cases. E.g. in the [nova-addon](https://github.com/Naoray/blueprint-nova-addon) I have to explicitly check for `nullable` modifiers and [remove the `required`](https://github.com/Naoray/blueprint-nova-addon/blob/master/src/Tasks/AddRegularFields.php#L75) rules from the array returned by `Rules::fromColumn()` method.

**Comment by jasonmccreary** [comment]
Yes, Blueprint will automatically mark a field `required` by default. You are welcome to change this in your own Generator if you wish.
