### ISSUE TITLE
Ability to create SoftDeletes Column and TimeStamps Columns with Timezone

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-shift/blueprint#13]
It would be helpful to be able to add those columns with the timezone.

1. `$table->timestampsTz();`  Adds nullable created_at and updated_at TIMESTAMP (with timezone) equivalent columns.
2. `$table->softDeletesTz();`  Adds a nullable deleted_at TIMESTAMP (with timezone) equivalent column for soft deletes.

**Comment by jasonmccreary** [comment]
Thanks. I'll get this cleaned up before version 1.0.

**Comment by jasonmccreary** [comment]
Both these timezone data types are now support and will generate the respective data type columns in the migrations.
