### ISSUE TITLE
Few issues when using belongsToMany

### ISSUE THREAD

**Issue by coldKingdom** [laravel-shift/blueprint#136]
In my draft I have setup an relationship like this:
```yaml
relationships:
      belongstoMany: Diary
```

There are a few things that I noticed that makes it unusable

**In the migration: 2020_04_20_111410_create_diary_journey_table.php**:

The class getting the name CreateDiaryJourneyPivotTable.
Pivot probably should not be there or vice versa?

The schema getting things a bit wrong
```php
        Schema::create('diary_journey', function (Blueprint $table) {
            $table->bigIncrements('Journey_id');
            $table->bigIncrements('diary_id');
        });
```
The correct one
```php
        Schema::create('diary_journey', function (Blueprint $table) {
            $table->bigInteger('journey_id');
            $table->bigInteger('diary_id');
        });
```

* bigIncrements should be bigInteger
* Journey_id should be journey_id

Otherwise it works very well as far I've tested it.
Thank you very much for this contribution!

**Comment by jasonmccreary** [comment]
Oh noes. I'll take a look later today to see if we can get this resolved. It was a recent addition and seems to be setup wrong.

Should be some simple changes, if you want to take a crack at the PR. 👍

**Comment by mikevandiepen** [comment]
I don't see "relations" anywhere in the documentation, Is this right?

**Comment by jasonmccreary** [comment]
Yes. You may define `relationships` on models. About 11 stars shy of working on documentation ;)

In the meantime, reference [this comment](https://github.com/laravel-shift/blueprint/pull/72#issuecomment-599174091) for more detail.
