### ISSUE TITLE
Use foreignId for belongsTo relationships in Laravel 7

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#137]
If the user is running Laravel 7, it'd be nice to generate the migration with the proper `foreign` key constraints.

Take a look at [this PR](https://github.com/laravel/framework/pull/32449) for the latest goodness in Laravel 7.

Also, as not all users may want to make foreign key constraints, we should probably introduce a `use_constraints` config option.

**Comment by mikevandiepen** [comment]
I would love to see this, just discovered the project and I'm already loving it!
