### ISSUE TITLE
Allow configuration to use `$guarded = [];`

### ISSUE THREAD

**Issue by lstables** [laravel-shift/blueprint#148]
This as probably come up in conversation somewhere, but I was unable to find anything.
First of all what a great package @jasonmccreary works a bloody treat, love the fact it creates factories, lot of time saving there in itself.

Anyway, each model is created with the `$fillable` attribute, it would be cool if you could specify what you wish to use i/e `$fillable` or `$guarded` with an empty array.

Just a thought, maybe something to add I dunno...

**Comment by jasonmccreary** [comment]
Yeah, the whole `fillable` vs `guarded` has become a `tabs` vs `spaces` thing. IMO, it's all broken and I hope to see it resolved in L8.

You are welcome to PR a `config` options of `use_guarded` or `unguarded_models` to toggle the code generate `$guarded = []` instead.

**Comment by lstables** [comment]
Its cool ill wait no rush. Just wanted to make a suggestion.

**Comment by jasonmccreary** [comment]
Yeah. I think it's something people would use. I just would want to make it a config option, not the default.

**Comment by lstables** [comment]
Yes i totally agree with you there. I just never have done a PR to an open source project and dont want to make a fool of myself lol
