### ISSUE TITLE
[IDEA] Allow replacement generator

### ISSUE THREAD

**Issue by ttomdewit** [laravel-shift/blueprint#150]
Hi 👋,

In your recent [Laracasts video](https://laracasts.com/series/guest-spotlight/episodes/9) you briefly mentioned extensibility.

Thinking out loud here. Would it be a good idea to allow replacements as well? Let's say I don't agree with how Models are generated, and I'd like to use 99% of Blueprint, but have my own Model implementation take over Blueprint's.

Is that something you'd consider supporting?

Cheers,

Tom

**Comment by jasonmccreary** [comment]
I suppose this would be possible if I were to register the core generators through the container or have some kind of special register methods allow for the override. But it creates kind of a slippery slope.

It's important to remember Blueprint goal is not 100%. It's actually much lower. So if Blueprint is doing 99% already, just do the other 1% by hand.

**Comment by ttomdewit** [comment]
I wholeheartedly agree with the percentage statements. Thought I’d share a rough idea I had. If there’s ever a time and place, I’d argue it might be worth revisiting.

Until then 🤘
