### ISSUE TITLE
undefined method in TestGenerator

### ISSUE THREAD

**Issue by MarkusBiggus** [laravel-shift/blueprint#151]
The yaml file is essentially the example code with names  changed for my models.

C:\inetpub\SANDBOX>composer update laravel-shift/blueprint

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating laravel-shift/blueprint (v1.5.1 => v1.6.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: artisaninweb/laravel-soap
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: beyondcode/laravel-websockets
Discovered Package: fideloper/proxy
Discovered Package: laravel-shift/blueprint
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Package manifest generated successfully.

C:\inetpub\SANDBOX>php artisan blueprint:build iam.yaml

In TestGenerator.php line 283:

  Call to undefined method Blueprint\Generators\TestGenerator::buildParameters()

**Comment by jasonmccreary** [comment]
This is fixed in `dev-master`. I am going to tag this shortly. If you want to point to `dev-master` in the meantime, it should be fixed.
