### ISSUE TITLE
Laravel Livewire component generation.

### ISSUE THREAD

**Issue by pushpak1300** [laravel-shift/blueprint#162]
I think there should be an option to generate Livewire Component through the draft file.

**Comment by jasonmccreary** [comment]
For sure. That'd be awesome. You should build one and register it with Blueprint. 👍

Docs coming soon. In the meantime, skip to the "Under the Hood" portion of [this video](https://laracasts.com/series/guest-spotlight/episodes/9) for some ideas.

**Comment by pushpak1300** [comment]
Thanks!

**Comment by silicahd** [comment]
I would pay for that feature.
