### ISSUE TITLE
Idea/question : generate HTML code inside views

### ISSUE THREAD

**Issue by pildit** [laravel-shift/blueprint#163]
Hi, 
i was playing with blueprint and i tried to generate a view for creating a Review model.
But I noticed there is only this inside the newly generated view :

`
@section('content')
    review.create template
@endsection
`

I was wondering if I did something wrong ? or it is not possible to get the HTML code for a <form> element with all the required inputs ?

**Comment by pildit** [comment]
Thanks!

**Comment by mixartemev** [comment]
> I do believe there are some other packages within the community that focus on making views. May want to search around.

Could you suggest some such packages?

**Comment by jasonmccreary** [comment]
@mixartemev don't know. If you can't find one, build one. 😉
