### ISSUE TITLE
Models are placed on root of the drive in Windows

### ISSUE THREAD

**Issue by AppGrind** [laravel-shift/blueprint#165]
This was noted on Windows 10 running Laragon with PHP 7.4
`blueprint:build` places Models in the root folder of the system (e.g C:\ or D:\) instead of the app folder of the project.

**Comment by jasonmccreary** [comment]
Did you customize any of the configuration? Was it just the models, or all generated files?

**Comment by jasonmccreary** [comment]
These was reported elsewhere, but somehow the issue resolved itself. Since I haven't heard back, I'll assume the same happened here.

**Comment by robertmarney** [comment]
I am presently having the same issue. Installed today and running on Win 10. Cleared my vendor folder and composer cache and reinstalled same issue.

**Comment by jasonmccreary** [comment]
This has been reported a few times. I've been unable to reproduce the issue.

Maybe if you could do a little debugging within the `ModelGenerator::getPath` method to see what/why it's starting with a `/`...

My assumption is some configuration or namespace is not getting set correctly on Windows for some reason...
