### ISSUE TITLE
 blueprint:trace, No models found if models are placed in Models directory

### ISSUE THREAD

**Issue by FaizAhmadSE** [laravel-shift/blueprint#166]

**Comment by FaizAhmadSE** [comment]
Sorry, i have found that we can change models directory in config file

**Comment by jasonmccreary** [comment]
Yes, currently the best way to do this would be to customize the `models_namespace` in your config. This would not only help the `trace` command, but also prevent you from having to prefix your model definitions in the draft file.

**Comment by tonjohn** [comment]
I've updated the config but trace is still unable to find the models. I've tried `'models_namespace' => 'Models',`, `App\\Models`, and `App\Models` to the same results.
