### ISSUE TITLE
belongsToMany generates duplicate migrations for pivot tables

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#167]
Given the following contents of `draft.yaml`:
```yaml
models:
  Company:
    name: string
    relationships:
      belongsToMany: Person
  Person:
    name: string
    relationships:
      belongsToMany: Company
```
Generates:
```sh
- database/migrations/2020_05_01_144405_create_companies_table.php
- database/migrations/2020_05_01_144405_create_company_person_table.php
- database/migrations/2020_05_01_144406_create_people_table.php
- database/migrations/2020_05_01_144406_create_company_person_table.php
- app/Company.php
- app/Person.php
- database/factories/CompanyFactory.php
- database/factories/PersonFactory.php
```
Observe that there are 2 migrations for the same pivot table.

Inspecting the two, we find a declaration with the same Class name: `CreateCompanyPersonTable`. This, of course, is a problem.

```sh
PHP Fatal error:  Cannot declare class CreateCompanyPersonTable, because the name is already in use in /Users/joostjacobs/Code/blueprint/database/migrations/2020_05_01_144406_create_company_person_table.php on line 7
```

Inspecting the two migrations, the only observable difference is the order in which the columns appear in the schema:

Inside `database/migrations/2020_05_01_144405_create_company_person_table.php
`:
```php
    public function up()
    {
        Schema::create('company_person', function (Blueprint $table) {
            $table->unsignedBigInteger('company_id');
            $table->unsignedBigInteger('person_id');
        });
    }
```

Inside `database/migrations/2020_05_01_144406_create_company_person_table.php`:
```php
    public function up()
    {
        Schema::create('company_person', function (Blueprint $table) {
            $table->unsignedBigInteger('person_id');
            $table->unsignedBigInteger('company_id');
        });
    }
```

**Comment by jasonmccreary** [comment]
Very nice catch. Thanks for reporting.

This should be pretty easy to resolve in the `MigrationGenerator` with an `array_unique` or tracking the already created tables. The main thing will be writing a test case for it. Which you have already provided a draft.

Feel free to take a stab at the PR. Otherwise, I'll pick it up early next week.

**Comment by axit-joost** [comment]
The weird thing is, the `MigrationGenerator` *already* tracks the created pivot tables:

https://github.com/laravel-shift/blueprint/blob/master/src/Generators/MigrationGenerator.php#L40-L58

**Comment by axit-joost** [comment]
Shouln't that `isset()` be an `in_array()`?

**Comment by jasonmccreary** [comment]
Probably. 😅 

Again, should be an easy bug to resolve. I'd just like to see a test added to back it up.
