### ISSUE TITLE
php artisan blueprint:init

### ISSUE THREAD

**Issue by ProjektGopher** [laravel-shift/blueprint#168]
Touches draft.yaml and fills with stub. Possibly run blueprint:trace as well?

**Comment by jasonmccreary** [comment]
Could be cool. Although I'd want to give it a name that aligned with the architectural vocabulary I'm using.

Maybe `blueprint:new` or `blueprint:start` or ...

**Comment by ProjektGopher** [comment]
That makes sense to me. I'll try to whip something together when I've got some time this weekend. Do I fork master for that, or is there a different branch I should use?

**Comment by jasonmccreary** [comment]
Cool. Yeah, Branch off `master`. Follow whatever pattern exists in the `ServiceProvider` to register a command.

Don't worry about _perfection_. Just get it functional. I'll review and tidy up the PR as necessary.

**Comment by Wowenko** [comment]
Hi @jasonmccreary I have tackled this but I'm having problems with the tests. Do you think is worth it to pull something like VFS to test the file creation?

**Comment by jasonmccreary** [comment]
Nope. You can swap the `File` facade and test that way. Go ahead and push what you have. I can update the test.
