### ISSUE TITLE
Idea for unable to revert changes to routes/web.php

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#170]
Currently, when you have a `controllers:` section in the `draft.yaml`, it will generate according to the statements therein, and it will also modify the existing `routes/web.php` file by appending to it.

Running a `blueprint:erase` will remove all generated files, but it currently cannot revert the changes made to the `routes/web.php` file, requiring one to do this manually. This gets old pretty quickly.

Idea:

1. Generate the routes to a `routes/blueprint.php` and add a `require_once('blueprint.php')` to the end of the `routes/web.php` file.
2. Track inside `.blueprint` that said `require_once()` statement is already added the `routes/web.php` file
3. Subsequent `blueprint:erase` and `blueprint:build` executions will not add that `require_once()` statement to `routes/web.php`, based on the existence of tracking information inside `.blueprint`.
4. Finally, 'blueprint:erase' can simply empty out `blueprint.php` and 'blueprint:build" can simply rewrite the contents of `blueprint.php`.

**Comment by jasonmccreary** [comment]
Thanks for the suggestion, but this is all mitigated with version control. Git will also be a way better tool for tracking changes than Blueprint. The `erase` command is merely a convenience.

If this is something you wish to tackle, my suggestion would be rather to inspect the previously generated controllers and attempt to remove the exact generated line from the routes file.

Again, wouldn't be 100%, but much better than imposing an `require` route file.
