### ISSUE TITLE
Multiple Relationships

### ISSUE THREAD

**Issue by jksteelman** [laravel-shift/blueprint#188]
Any interest in finding a way to support multiple relationships of the same type? Since its yaml, the parser stops when it hits invalid yaml like:

     models:
          post:
              relationships:
                   hasMany: Image
                   hasMany: Comment

Inverting the definition would be ideal `Image: hasMany` but would break previous blueprints. Allowing a psuedo-key like `hasMany_1: Image` could work. I dunno. Thanks for a great tool.

**Comment by jasonmccreary** [comment]
This is possible. You just specify them as a comma separate list. Check [the docs](https://blueprint.laravelshift.com/docs/model-relationships/) for full details.

But in your case:

```yaml
models:
  Post:
    relationships:
      hasMany: Image, Comment
```

**Comment by jksteelman** [comment]
Totally missed that. Thanks!
