### ISSUE TITLE
Getting a permission error while trying to build 

### ISSUE THREAD

**Issue by fawzanm** [laravel-shift/blueprint#193]
PHP 7.4.5
Laravel v7.10.3
Blueprint v1.10.0
macOS 10.15.4 

I am just getting started with blueprint. I tried a very simple example with the following `draft.yaml` file. 

```
models:
  Post:
    title: string:400
    published_at: timestamp nullable
```

When I run the command `php artisan blueprint:build draft.yaml` I get the following error. 

```

   ErrorException 

  file_put_contents(/Post.php): failed to open stream: Read-only file system

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
    129|      * @return int|bool
    130|      */
    131|     public function put($path, $contents, $lock = false)
    132|     {
  > 133|         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    134|     }
    135| 
    136|     /**
    137|      * Write the contents of a file, replacing it atomically if it already exists.

      [2m+19 vendor frames [22m
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

However, the migration file is created under the `database/migrations` directory.

**Comment by jasonmccreary** [comment]
I assume you are on Windows? Someone else reported this issue in #165.

Could confirm this is a similar issue and let me know if you customized the Blueprint config?

**Comment by fawzanm** [comment]
@jasonmccreary sorry, I didn't specify my OS. I am on macOS Catalina. I'll update the issue.

**Comment by jasonmccreary** [comment]
Interesting.

Let me take a closer look at the code. However, is it just `models`? Can you try with only a controller and see if it throws the same error?

**Comment by fawzanm** [comment]
@jasonmccreary It's just for the models, controllers are created without an issue for the following `draft.yaml` file. 
```

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts

```

**Comment by fawzanm** [comment]
Ok, this is wired, I just reverted in the same setup and added the model and it works now. :/

**Comment by jasonmccreary** [comment]
No worries. What do you mean "reverted"?

**Comment by fawzanm** [comment]
Well, I was trying it in a new branch of my project and it didn't work. I opened the issue and stashed all the changes from git. After you asked me to build it for a model I then did that, it worked and again I stashed my changes. Then I ran it for the controller and voila!

**Comment by jasonmccreary** [comment]
Did you run `composer update` or anything during that time?

I'd like to try and pinpoint what it was if you could try and backtrack.

- Had you initially published or changed the Blueprint config file?
- Was the sample draft file the first thing you tried to do?
- Can you remove Blueprint, reinstall, and try again?

**Comment by fawzanm** [comment]
**Had you initially published or changed the Blueprint config file?**
I initially went with the default, didn't publish the config. It didn't work. Then I published and gave couple of tries. They all seem to fail so I gave up. 

**Was the sample draft file the first thing you tried to do?**
No. I started with one of my models. I just tried to add the model and couple of controller methods. It failed on model. 

**Can you remove Blueprint, reinstall, and try again?**
I did do the composer update a couple of times, but I didn't notice any version change in blueprint. 

It works for me now, if you think I should uninstall and reinstall, I can still give it a try.

**Comment by jasonmccreary** [comment]
Meh, I'll consider it some kind of fluke. Wish I knew the issue though.

Anyway, closing. If you happen to stumble upon what it was, do comment back.

**Comment by gmgarrison** [comment]
I'm actually running into a related issue. I'm on Mojave, PHP 7.4.6 and just installed Blueprint this week with composer. I've tried with `models_namespace = 'Models'` (which is my preference) but also with it blank and see get this error:

  ```
ErrorException

  file_put_contents(/Enum.php): failed to open stream: Permission denied

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:135
    131|      * @return int|bool
    132|      */
    133|     public function put($path, $contents, $lock = false)
    134|     {
  > 135|         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    136|     }
    137|
    138|     /**
    139|      * Write the contents of a file, replacing it atomically if it already exists.

      +19 vendor frames
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

I ran it with sudo just to see what would happen and it dropped the model files in the top-most folder, as indicated. Is there some other config I'm missing?

Blueprint does, however, generate the correctly-placed migrations, factories and seeders.
