### ISSUE TITLE
Mockery errors while running test suite

### ISSUE THREAD

**Issue by kreeves** [laravel-shift/blueprint#195]
Possibly just user error, but I'm struggling to run the test suite locally.

Running in a docker container with PHP 7.3.6, PHPUnit 9.1.4.

1. Run `composer install`
2. Run `vendor/bin/phpunit`

<details>
<summary>PHPUnit error</summary>
71) Tests\Feature\Generators\TestGeneratorTest::output_generates_test_for_controller_tree_using_cached_model
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_4::put('tests/Feature/Http/Controllers/UserControllerTest.php', '<?php

namespace Tests\Feature\Http\Controllers;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use JMac\Testing\Traits\AdditionalAssertions;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\UserController
 */
class UserControllerTest extends TestCase
{
    use AdditionalAssertions, RefreshDatabase, WithFaker;

    /**
     * @test
     */
    public function store_uses_form_request_validation()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\UserController::class,
            'store',
            \App\Http\Requests\UserControllerStoreRequest::class
        );
    }

    /**
     * @test
     */
    public function store_saves_and_redirects()
    {
        $email = $this->faker->safeEmail;
        $password = $this->faker->password;

        $response = $this->post(route('user.store'), [
            'email' => $email,
            'password' => $password,
        ]);

        $users = User::query()
            ->where('email', $email)
            ->where('password', $password)
            ->get();
        $this->assertCount(1, $users);
        $user = $users->first();

        $response->assertRedirect(route('dashboard'));
        $response->assertSessionHas('user.email', $user->email);
    }
}
'). Either the method was unexpected or its arguments matched no expected argument list for this method

/var/www/html/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:92
/var/www/html/src/Generators/TestGenerator.php:59
/var/www/html/tests/Feature/Generator/TestGeneratorTest.php:139
</details>

**Comment by kreeves** [comment]
Ran into this while trying to work a fix for #194

**Comment by jasonmccreary** [comment]
What platform are you on? My guess is it's a spacing issue. But that should be resolved by a recent version.

**Comment by kreeves** [comment]
Was running 1.9. Upgraded to 1.10 and re-ran and tests all pass!

Thanks!
