### ISSUE TITLE
Generate Seeder when generating factory

### ISSUE THREAD

**Issue by ProjektGopher** [laravel-shift/blueprint#198]
### Synopsis:
When generating a model factory, also generate a database table seeder

### Proposed Syntax:
No change in syntax

### Expected Behavior:
Create seeder from stub (basically just factory(Model::class, 10)->create();)
Add to DatabaseSeeder@run (won't be able to delete in blueprint:erase - much like generated routes)

**Comment by jasonmccreary** [comment]
I like it and am open to adding it. However, I don't think devs _want_ a seeder for every model generated.

As such, I'd like to come up with a way to trigger the generation of a seeder, either with _config_, _option_, or syntax.

Any ideas?

**Comment by ProjektGopher** [comment]
Would adding a 'seeder' shorthand to the model def mess with the list of tokens used to generate everything else?

I'm also wondering if that even matters, since if they don't want it, they probably wont be running db:seed then anyways.

Thoughts?

**Comment by jasonmccreary** [comment]
I'm reluctant to add syntax. If I did, it would be its own section.

For example:

```yaml
models:
  # ...

seeders: Post, User, Comment

controllers:
  # ...
```

Or its own command since it's such lightweight thing.

For example: `blueprint:build --seeder Post User Comment`

**Comment by ProjektGopher** [comment]
Just in terms of the API I would prefer to use while making something, I think giving seeders their own section would make the most sense. When I'm trying to get my draft.yaml file just right, I cycle between "art blueprint:build" and "git reset --hard && git clean -df" a lot. I feel like adding more flags would hurt that process. Not sure if others work the same way as I do there...

**Comment by jasonmccreary** [comment]
I'm fine with adding a "seeders" section, but the more I think about it, the more I'd want it under models.

So, let's move forward with this syntax:

```yaml
models:
  Post:
    # ...
  Comment:
    # ...
  Media:
    # ...
  seeders: Post, Comment
```

**Comment by ProjektGopher** [comment]
I actually really like this idea the more I think about it. This way we can add something like Post:50 to tell blueprint how many records to create

**Comment by jasonmccreary** [comment]
Sounds good. Feel free to start it with an open PR. Otherwise, I'll possibly work on it during Thursday's live stream.

**Comment by jasonmccreary** [comment]
@ProjektGopher went ahead and got this started in the live-stream. I think it provides a good foundation, so I am going to close this.

However, if a more advanced syntax is needed (e.g. `Post:50`), you are welcome to open a new issue or PR to add it.
