### ISSUE TITLE
Polymorphic Relations are not supported

### ISSUE THREAD

**Issue by RahulDey12** [laravel-shift/blueprint#199]
### Synopsis:
Polymorphic Relations are not supported

### Proposed Syntax:
`morphTo: attendable`
`morphMany: Attendance`

### Expected Behavior:

That should add a Polymorphic relation [](https://laravel.com/docs/7.x/eloquent-relationships#many-to-many-polymorphic-relations)

**Comment by jasonmccreary** [comment]
I like it. Should be a pretty easy addition if you'd like to try opening a PR for it. No worries if it doesn't have tests, I can add them afterwards.

Otherwise, I'll open this up to the community...
