### ISSUE TITLE
Make Blueprint class extensible

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#2]
While the `Blueprint` class has methods to register additional _lexers_ and _generators_ it is created within the command and as such not readily extensible.

Potential options:

- _resolved_ as a `singleton` to share the same object with other components
- allow publishing of a configuration file to register additional functionality

**Comment by ttomdewit** [comment]
You could consider https://laravel.com/docs/6.x/providers#deferred-providers and see if you can "tag" generator packages as such. I think from within the main Blueprint package you can find all tagged services.

Make sure these adhere to a common contract so the main package doesn't really know what generators are available, it just knows how to use them.
