### ISSUE TITLE
Notification Vs Mail

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-shift/blueprint#20]
I see a stament 

`send: ReviewNotification to post.author`

Which means that it need to Create a Notification class

`send: ReviewMail to post.author`

Which means that it need to Create a Mail class

**Comment by jasonmccreary** [comment]
Yes. I think a little convention here would nice to distinguish which should be created. I'll add this to the list of tweaks post v1.

**Comment by andreich1980** [comment]
Sorry for offtopic but where does it get the `.author` part? 
![image](https://user-images.githubusercontent.com/17148882/71413438-3c175000-2663-11ea-98b4-975d0fd49711.png)
I see that it sends a notification to the post's author but there are no `author_id` column in the posts model. 
What am I missing here?

**Comment by jasonmccreary** [comment]
You are right. This example is missing the `author` field.

At the moment, to provide flexibility, Blueprint does not validate the dot notation, it is simply converted to arrow notation.
