### ISSUE TITLE
running build command as doc says trows file does not exist

### ISSUE THREAD

**Issue by DigiD3ar** [laravel-shift/blueprint#203]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Blueprint Version: 1.10
- Platform: Mac

### Description:
when using php artisan blueprint:build [draft] as doc says, throws 
file does not exist
when running php artisan blueprint:build draft.yaml
Argument 1 passed to Blueprint\Lexers\StatementLexer::analyze() must be of the type array, null given, called in /Applications/MAMP/htdocs/original/vendor/laravelshift/blueprint/src/Lexers/ControllerLexer.php on line 42

### Steps To Reproduce:
just created new project and added blueprint, new draft.yaml , and run php artisan blueprint:build [draft] as doc says

**Comment by jasonmccreary** [comment]
The `[draft]` is common syntax for a placeholder of an optional argument.

So you either leave this off or replace it with your custom draft filename, such as `example.yaml`

**Comment by DigiD3ar** [comment]
tried with with draft.yaml, with 'draft.yaml' too even with [draft.yaml] and keeps telling me file does not exist. draft.yaml is in project root beside artisan

**Comment by jasonmccreary** [comment]
Sorry, I am unable to reproduce this issue.

A few things to try:

- you have a draft file named `draft.yaml` and using `php artisan blueprint:build` OR using `php artisan blueprint:build your-custom-named-draft-file.yaml`
- your draft file is in your project root, with `artisan`.
- your draft file has the correct syntax


If the problem persists, feel free to comment back with your exact commands and draft file definition.

**Comment by DigiD3ar** [comment]
reviewed my draft file, and  found two empty methods in my controllers. deleted them and everything worked. there isnt any warning for that?
