### ISSUE TITLE
Controller: resource: api shorthand should leverage Route::apiResource

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#205]
### Synopsis:
Currently, when you use the `resource: api` shorthand in the `controllers:` section, a route is generated like so:
```php
Route::resource('certificate', 'CertificateController')->except('create', 'edit');
```
However, Laravel has a documented method for [API Resource Routes](https://laravel.com/docs/7.x/controllers#restful-partial-resource-routes)

### Proposed Syntax:
It should generate this instead:
```php
Route::apiResource('certificate', 'CertificateController');
```

### Expected Behavior:
The behavior will be exactly the same, but the generated code is more 'on point' so to speak.

**Comment by jasonmccreary** [comment]
I consider this implied as part of #206.

Closing.
