### ISSUE TITLE
Controller: resource: api shorthand should add routes to routes/api.php

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#206]
### Synopsis:
Currently, when using the `resource:api` shorthand in the `controllers:` section, routes will be added to `routes/web.php`. However, it would be better suited appending them to `routes/api.php`.

Defining them there will make sure the correct middleware is applied (or omitted), so that you can immediately consume the API from the command line, using Curl or HTTPie, without running into CSRF problems.

Also, as mentioned in #205 they should be a `Route::apiResource()`

### Proposed Syntax:
So instead of:

***routes/web.php***
```php
Route::resource('certificate-type', 'CertificateTypeController')->except('create', 'edit');
```
We need to generate:

***routes/api.php***
```php
Route::apiResource('certificate-type', 'CertificateTypeController');
```

### Expected Behavior:

The DX for a developer would greatly increase.

From current behavior:
```sh
❯ http post https://blueprint.test/certificate-type foo=bar                                                                                                             42%
HTTP/1.1 419 unknown status
Cache-Control: no-cache, private
Connection: keep-alive
Content-Type: application/json
Date: Fri, 15 May 2020 07:20:55 GMT
Server: nginx/1.17.3
Set-Cookie: laravel_session=eyJpdiI6Ii9zRnliNGx5NnNxVVdnNWpPWkNOK1E9PSIsInZhbHVlIjoiOFJnREtmeXgxQU5HVnZKTlU1NUJNOHVrY2hIREZMZW9JT2hFb0g0amRwUFNzRHFyOXVpZWtxcnJQUnhndEViQyIsIm1hYyI6IjVhYTJlZTBmOGFjMmZhOGVhMGRmNDE0NmVmM2IyMGRlMzlkNjNmMGM1MjQwODY4YzEzNDRlYzM3ZTE4NTk5NmEifQ%3D%3D; expires=Fri, 15-May-2020 09:20:55 GMT; Max-Age=7200; path=/; httponly; samesite=lax
Transfer-Encoding: chunked
X-Powered-By: PHP/7.4.4

{
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
    "file": "/Users/joostjacobs/code/blueprint/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 226,
    "message": "CSRF token mismatch.",
    "trace": [
        {
...
```

would become this behavior:

```sh
❯ http post https://blueprint.test/api/certificate-type foo=bar                                                                                                         42%
HTTP/1.1 422 Unprocessable Entity
Cache-Control: no-cache, private
Connection: keep-alive
Content-Type: application/json
Date: Fri, 15 May 2020 07:22:21 GMT
Server: nginx/1.17.3
Transfer-Encoding: chunked
X-Powered-By: PHP/7.4.4
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59

{
    "errors": {
        "name": [
            "The name field is required."
        ]
    },
    "message": "The given data was invalid."
}
```

**Comment by jasonmccreary** [comment]
I agree with this convention. I thought we had an open issue for it somewhere already, but I guess not. My only hesitation would be not all developers leverage the `api` middleware.

Nonetheless, I think it's a good convention for Blueprint to follow.

I'll take this as a good first issue as it shouldn't be too hard to generate in the `RouteGenerator`.

However, the tricky will be _knowing_ that the controller is an `api` resource. I believe the `ControllerLexer` flags a controller as _api_. If not, that could be added for convenience.
