### ISSUE TITLE
Allow to specify the restriction type on a foreign key

### ISSUE THREAD

**Issue by drsdre** [laravel-shift/blueprint#213]
### Synopsis:
According the documentation, Blueprint 'will generate code to add the reference and cascade "on delete" constraints.' It would be very handy if the type of restriction could be specified being cascade, restrict, set_null, no_action or set_default.

### Proposed Syntax:
Allow the third parameter after foreign table to describe the restriction.

`  foreign_table_id: foreign_table:<restriction type> nullable`

### Expected Behavior:
Definition:
`domain_id: id:domain:set_null nullable`

Should generate the following code:
`$table->foreignId('domain_id')->nullable()->constrained()->onDelete('SET NULL');`

In particular I want to point out that the 'nullable()' instruction should come before 'constrainted()' which is currently not the case.

**Comment by jasonmccreary** [comment]
I don't really want to add even more syntax to the `foreign` key statements. Tbh, I've spent more time on this feature than it deserves. Furthermore, it something easy to change after the fact.

With that said, I understand that if you don't use `on delete` constraints the current output lessens the experience.

So I'd be open to adding a config option where you specific the cascade type (`null`, `delete`, etc)

Also, if there is a bug with the `nullable` chaining, please let me know so I can open a separate **bug**.

**Comment by drsdre** [comment]
Developing a feature that only allows you to specify a default restriction type, honestly I feel this won't be development time spend well.

Being able to specify the restriction type is part of the database model design. I agree it's easy to change afterwards, however Blueprint is missing an essential part of describing the data structure.

In most database designs I will use 3 types of restrictions regularly:
1. Cascade: For example a domain which has dns records. Whenever a domain item get's removed, I expect the DNS records for that domain to be removed too.
2. Restrict: For example the domain table which has a responsible user and belongs to an organisation. In this case I want to restrict the user or organisation to be deleted to prevent unwanted data loss.
3. Optional null: For example a domain table that can have an optional link to hosting service record. When the hosting service get's removed, I want the domain to stay but have the link set to null.

I'm going to have a look at the code to see what is possible.

**Comment by drsdre** [comment]
Regarding the bug with 'nullable' in a foreign key, this is how Blueprint creates the migration in Laravel 7:

`$table->foreignId('brand_id')->constrained()->cascadeOnDelete()->nullable(); `

Nullable after constrained will produce an error as constrained does not return a column definition. Nullable should be added to the chain before the 'contrained' function:

`$table->foreignId('brand_id')->nullable()->constrained()->cascadeOnDelete();`

**Comment by jasonmccreary** [comment]
I have created a bug for the `nullable` chaining.

As far as the inline syntax for the _cascade type_, I will leave that open to the community to add.
