### ISSUE TITLE
DBALException on ENUM type when running blueprint:trace on existing project

### ISSUE THREAD

**Issue by furtherance** [laravel-shift/blueprint#218]
- Laravel Version: v6.18.14
- PHP Version: 7.2.19
- Blueprint Version: v1.11.0
- Doctrine/Dbal Version: v2.10.2
- Platform: Windows / Laragon

### Description: 
Running blueprint:trace on an existing project with enum data type on one of the columns in an existing table throws an exception;
**Doctrine\DBAL\DBALException  : Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.**

### Steps To Reproduce:
Run blueprint:trace command in a project that has a table containing an enum column.
Example table;
```
    Schema::create('messages', function (Blueprint $table) {
        $table->increments('id');
        $table->enum('type', ['SMS', 'Email', 'Push']);
        $table->mediumText('message');
        $table->timestamp('sent_at');
        $table->engine = 'InnoDB';
    });
```
### Workaround:
I was able to run blueprint:trace after altering the enum column to string instead. To do that successfully I had to add the following to my up() function before the schema change call;
**DB::connection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');**
	
### Stack Trace:	

```
>php artisan blueprint:trace -v

   Doctrine\DBAL\DBALException  : Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

  at \vendor\doctrine\dbal\lib\Doctrine\DBAL\Platforms\AbstractPlatform.php:440
    436| 
    437|         $dbType = strtolower($dbType);
    438| 
    439|         if (! isset($this->doctrineTypeMapping[$dbType])) {
  > 440|             throw new DBALException('Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.');
    441|         }
    442| 
    443|         return $this->doctrineTypeMapping[$dbType];
    444|     }

  Exception trace:

  1   Doctrine\DBAL\Platforms\AbstractPlatform::getDoctrineTypeMapping("enum")
      \vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\MySqlSchemaManager.php:128

  2   Doctrine\DBAL\Schema\MySqlSchemaManager::_getPortableTableColumnDefinition()
      \vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\AbstractSchemaManager.php:810

  3   Doctrine\DBAL\Schema\AbstractSchemaManager::_getPortableTableColumnList("messages", "db")
      \vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\AbstractSchemaManager.php:167

  4   Doctrine\DBAL\Schema\AbstractSchemaManager::listTableColumns("messages", "db")
      \vendor\laravel-shift\blueprint\src\Commands\TraceCommand.php:123

  5   Blueprint\Commands\TraceCommand::extractColumns(Object(App\Models\Message))
      \vendor\laravel-shift\blueprint\src\Commands\TraceCommand.php:55

  6   Blueprint\Commands\TraceCommand::handle()
      \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  7   call_user_func_array([])
      \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  8   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      \vendor\laravel\framework\src\Illuminate\Container\Util.php:36

  9   Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
      \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:90

  10  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:34

  11  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      \vendor\laravel\framework\src\Illuminate\Container\Container.php:590

  12  Illuminate\Container\Container::call()
      \vendor\laravel\framework\src\Illuminate\Console\Command.php:134

  13  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      \vendor\symfony\console\Command\Command.php:255

  14  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      \vendor\laravel\framework\src\Illuminate\Console\Command.php:121

  15  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      \vendor\symfony\console\Application.php:1001

  16  Symfony\Component\Console\Application::doRunCommand(Object(Blueprint\Commands\TraceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      \vendor\symfony\console\Application.php:271

  17  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      \vendor\symfony\console\Application.php:147

  18  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      \vendor\laravel\framework\src\Illuminate\Console\Application.php:93

  19  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      \vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:131

  20  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      \artisan:37
```

**Comment by axit-joost** [comment]
I do believe that there's some TODO somewhere in the code:

https://github.com/laravel-shift/blueprint/blob/c82a8c509be31584958919f8e1231cb55126da2f/src/Commands/TraceCommand.php#L161

Enums on database level are a world of hurt in my humble opinion. I get bitten by them every single time I touch some old database schema's that I've been working pro-actively to refactor them.

That DoctorineMapping that you are instructing, basically maps `enum` to `string`, so it will end up as a string in your `.blueprint` file. If you were to regenerate stuff, it would ultimately become a model and migration using a string, therefore losing the database `enum` entirely.

I'm not sure if this is an actionable issue or bug even for Blueprint.

My advice would be to eradicate all uses of an enum in your current migrations (either in migrations that you already have or creating a migration altering them from enum to a varchar.

You can't use the `change()` function that the Schema Builder supplies, because that uses DBAL behind the scenes also, which leads to the same Exception. This is also in Laravel's documentation:

https://laravel.com/docs/7.x/migrations#modifying-columns
> Only the following column types can be "changed": bigInteger, binary, boolean, date, dateTime, dateTimeTz, decimal, integer, json, longText, mediumText, smallInteger, string, text, time, unsignedBigInteger, unsignedInteger, unsignedSmallInteger and uuid.

So you end up doing stuff like:
```php
DB::statement('ALTER TABLE some_table CHANGE COLUMN some_enum some_enum your-data-type NOT NULL DEFAULT your-default;');
```
And you do that for all instances of enums in your database.

Additionally, I would recommend reading up on how other developers handle enums, like the folks at Spatie do:

* https://stitcher.io/blog/php-enums
* https://github.com/spatie/enum
* https://github.com/spatie/laravel-enum

**Comment by jasonmccreary** [comment]
@furtherance there should be basic support for this now if you'd like to try it out by updating to the latest version.
