### ISSUE TITLE
Treat foreign keys as integers

### ISSUE THREAD

**Issue by ryancco** [laravel-shift/blueprint#219]
### Synopsis:
Treat foreign keys as integers. Whether this be in specific cases, such as when the relationships are inferred from a child of the `relationships` key, when the "special" `id` column/attribute type is specified on the foreign table or just as a sane default when there is a foreign key of any sort.

Currently, foreign keys are being represented as strings in model class level docblocks. Foreign keys are also not being cast to integer type. As well, foreign keys default generated faker data is of type `word`.

### Expected Behavior:
- Foreign keys will be cast to integer type in the model `$casts` attribute
- Foreign keys' type will be `integer` in model class level docblocks
- Foreign keys' default factory data will be a factory generated instance of the related model

**Comment by jasonmccreary** [comment]
I think you were probably attempting to use the `foreign` shorthand which didn't exist. However, this has since been added. So I believe most of these issues should be resolved.

If not, please open a new issue with your _draft file_ and unexpected behavior.
