### ISSUE TITLE
Is the Closure necessary, the command class is resolved out of the container anyway so the constructor dependencies will be injected?

### ISSUE THREAD

**Issue by ryangjchandler** [laravel-shift/blueprint#22]
https://github.com/laravel-shift/blueprint/blob/037f5b995539102c5eaabbff8377374f9921bd28/src/BlueprintServiceProvider.php#L31-L33

**Comment by jasonmccreary** [comment]
Probably not. I have done it this way to facilitate testing using TestBench. We'll see if it helps or not. Otherwise, allow the container to resolve these accordingly.
