### ISSUE TITLE
Early logo ideas

### ISSUE THREAD

**Issue by minthemiddle** [laravel-shift/blueprint#23]
Just two rough logo ideas for Blueprint.
Probably not more than just some inspiration or base for discussion as they're just the obvious and super simple.

![Blueprint-01](https://user-images.githubusercontent.com/1950766/69352269-ec68f180-0c7c-11ea-8e02-86f4d5ed4ba2.png)

![Blueprint-02](https://user-images.githubusercontent.com/1950766/69352273-ef63e200-0c7c-11ea-8a12-36ce24fa60e0.png)

**Comment by jasonmccreary** [comment]
Awesome. I'll demo these in the live-stream momentarily. They're both good, but I probably like a hybrid of the two (lowercase + more lines).

**Comment by jasonmccreary** [comment]
@minthemiddle you want to pair up on this and we'll knock something out for v1?

**Comment by minthemiddle** [comment]
@jasonmccreary Sorry, have been ill for some days. I'll put the designs on Figma tomorrow (Berlin/Germany) and share it with you. Find my contact on my profile for live pairing.

**Comment by jasonmccreary** [comment]
I think it's fine for an initial version. How can I get a copy to add to the `README.md` as that will serve as the initial documentation.

If it becomes popular, we can recreate the additional sizes.

**Comment by minthemiddle** [comment]
Here you go…

<img width="1071" alt="blueprint-logo" src="https://user-images.githubusercontent.com/1950766/69678428-d2c51100-10a5-11ea-9994-f952b21f43b4.png">

**Comment by jasonmccreary** [comment]
Awesome. I am now using this in the documentation. If _Blueprint_ gains an active user base, we can spend more refining the design.

At that time, I will open a new issue.
