### ISSUE TITLE
Ability to override Test Generation?

### ISSUE THREAD

**Issue by dmason30** [laravel-shift/blueprint#236]
I would like to create a separate addon package that generates the tests using https://github.com/pestphp/pest. But currently there is no way to override or remove the current TestGenerater registered here:

https://github.com/laravel-shift/blueprint/blob/80e47619d27e8bce0f4a32e81c87c47a3a6357e3/src/BlueprintServiceProvider.php#L85

I am happy to PR but not sure if best to bind the `TestGenerator` to the container so it can be overridden or to add ability to `unregisterGenerator` from the `Blueprint` class.

**Comment by jasonmccreary** [comment]
Super cool.

Yeah, you have brought up a lot of _ideas_. I see two distinct paths.

1. Disabling a set of code generation (e.g. _tests_)
2. Overriding an existing generator with your own

While the first is an option, it doesn't really fit your use case as much as the second.

So, if you'd like to open a PR which adds a `swapGenerator`. Similar to how `swap` works within Laravel testing, it would take an argument of the _abstract_ and the _concrete_.

For example:

```php
$blueprint->swapGenerator(
    \Blueprint\Generators\TestGenerator::class,
    new \DMason\PestPhp\TestGenerator($app['files])
);
```

**Comment by dmason30** [comment]
@jasonmccreary So I have started this and below is the simplest solution I have come up with is to have the concrete as a key in the generators array: 

```php
public function registerGenerator(Generator $generator)
{
    $concrete = get_class($generator);
    $this->generators[$concrete] = $generator;
}

public function swapGenerator(string $concrete, Generator $generator)
{
    $this->generators[$concrete] = $generator;
}
```

However, this approach means that you wouldn't be able to register multiples of the same generator with different args:

```php
$bluepring->registerGenerator(new CustomGenerator($app['files']);
$bluepring->registerGenerator(new CustomGenerator($differentFilesArray); // This would overrwrite the above registration. 
 ```
Which also broke `BlueprintTest::generate_uses_registered_generators_and_returns_generated_files` for the same reason as it creates to mock instances of the same class (interface) where `get_class` returns `Mockery_0_Blueprint_Contracts_Generator`. Easily fixable to create the second mock from a fixture child class. 

**Alternative**
The other solution would leave the generators array as is but when `swapGenerator` is called it would have to loop through each generator and check the instance:

```php
public function swapGenerator(string $concrete, Generator $generator)
{
    foreach($this->generators as $key => $generator) {
        if ($generator instanceof $concrete) {
            unset($generator[$key]);
        }
    }
    
    $this->registerGenerator($generator);
}
```

**Comment by jasonmccreary** [comment]
I don't think we need to worry about these additional cases at this time.

For now, _do the simplest thing that can possible work_. Which is the "alternative" you mentioned. That's more inline with that I expected anyway.
