### ISSUE TITLE
default values (for enum) requires (sometimes) quotation marks

### ISSUE THREAD

**Issue by ndeblauw** [laravel-shift/blueprint#263]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Blueprint Version: 1.13.0
- Mysql 5.7.18 (x64)
- Platform: Windows

### Description:
Setting a default value requires quotation marks
* Gives error
`preferred_contact_method: enum:mail,sms,phone,whatsapp,messenger default:phone`
* Is correct
`preferred_contact_method: enum:mail,sms,phone,whatsapp,messenger default:'phone'`

Though not really a problem, it's a bit counter intuitive as the enum itself doesn't require this. I suggest taking a step back and deciding whether 
* you're going to add _just a little bit more of magic methods_ in the default functionality or 
* to document the behaviour of default a bit better

Why the error, well this is the migration that is generation?
![image](https://user-images.githubusercontent.com/4344869/84125623-14fbe180-aa3d-11ea-82fb-b141033ac21e.png)

### Steps To Reproduce:
see above

### draft.yaml:
see above

**Comment by jasonmccreary** [comment]
I think this is the correct behavior. `default` takes a literal value. So if you define `0` it will generate `default(0)`. If you pass define `'0'`, it will generate `default('0')`.

I agree this is a bit different than the other modifiers. However, give the above, it does make sense as to _why_. Nonetheless, I will look into modifying the docs.

**Comment by jasonmccreary** [comment]
This has been clarified on the [Model Data Types](https://blueprint.laravelshift.com/docs/model-data-types/) section. Let me know how it reads.
