### ISSUE TITLE
Support changes to existing models

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#3]
Blueprint only generates new _Model_ components. As such, assumptions have been made about file naming, migration schema, and class existence.

Ideally, Blueprint would also append existing components with new, updated, or removed columns.

**Comment by ttomdewit** [comment]
You might consider looking into https://github.com/nikic/PHP-Parser for this.

**Comment by mikevandiepen** [comment]
> 
> 
> You might consider looking into https://github.com/nikic/PHP-Parser for this.

I second this. I've worked quite a bit with nikic/php-parser and it is quite a useful tool. I assume this issues is directed at the fact that for example the `User` model / migration can not be changed since it already exists?

**Comment by mikevandiepen** [comment]
Ideally we would generate the classes as well with `nikic/PHP-Parser` take a look at their [AST Builder](https://github.com/nikic/PHP-Parser/blob/master/doc/component/AST_builders.markdown).

I'm going to make a repository where I do an attempt for model generation with PhpParser to determine whether it is maybe a way to continue.

**Comment by mikevandiepen** [comment]
Created this within an hour; https://github.com/mikevandiepen/BlueprintPHPParser
This is a bootleg to generate models with `Nikic/PHP-Parser`. You can contact me if you'd like me to implement this we can maybe go over some details.

**Comment by jasonmccreary** [comment]
Great. What is the initial use case for Blueprint?

**Comment by mikevandiepen** [comment]
Don't see it as a replacement, Im just working out how this parser would be if it was build with `nikic/php-parser`. Since I'd like the posibility to update existing models, migrations, controllers etc a lot of changes need to be made to the current codebase. I think I can explain my take on it maybe better through private chat / dm? Hmu if you're interested in more details

**Comment by jasonmccreary** [comment]
It's really not a priority for Blueprint to change existing code. So these use cases would be limited, maybe to models and controllers, but probably nothing else.

As such, I'm not looking to rewrite Blueprint to use this parser.

If you'd like determine a specific use case of changing something existing, for example adding "SoftDeletes" functionality to a model, let's open another issue and try then.

With that said, I am going to close this as it was really a placeholder issue from the beginning with no clear requirements.
