### ISSUE TITLE
Feature request: reverse engineering

### ISSUE THREAD

**Issue by bomshteyn** [laravel-shift/blueprint#30]
First thanks for this amazing tool!!!

**Idea**:
Sometimes we have projects that are 80% similar (data / workflow) to something else we built in the past, it would be really cool if we can do the following:

- have a blueprint file reverse-engineered from an existing project
- import it to the new project
- change the 20% that is different and bootup the new project that way.

**Comment by jasonmccreary** [comment]
I plan to build something that does this for existing models. But I'm not sure about controllers. That'd be challenge and never 100%.

With that said, you could create a _draft template_. Then share it among projects and change the small pieces. A little upfront work, but would do what you need.

If Blueprint becomes more popular, I am already envisioning a _registry_ of `draft` files the community could share for common components (Blog, Order, Team, Address, etc).

**Comment by jasonmccreary** [comment]
I believe the code aspect of this is covered by the new `trace` command in #69.

In addition, I still plan to open some kind of _archive_ or _registry_ to make it easier to share `draft` files for common generated components once this package reaches 10,000 download.
