### ISSUE TITLE
Add additional methods to generated Models.

### ISSUE THREAD

**Issue by WesleyVroegh** [laravel-shift/blueprint#322]
### Synopsis:
Generate custom methods for models.

### Proposed Syntax:
```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp
    methods: 
        myCustomMethod
```

### Expected Behavior:
The Lexers cannot read the draft file like shown above, because of the explicit typehint used in the buildColumns method, which is a good thing, an array cannot be parsed and should not be accepted when it is not a column.

To make it possible to add custom methods to generated models (in this case Post), i would like to suggest to add another item to the draft.yaml file as shown in the proposed syntax above.

With this, the Tree class containing the `$registry` can contain another option called 'methods' or 'customMethods' under 'models' `$registry['models']['methods']` or `$registry['models']['customMethods']`which will be occupied with the (parsed) array found in the draft file under 'methods' for Post.

The Model class could then get another method called `methods` or `customMethods` or something similar.
So when the models are instantiated for the Registry tree, these can also be added to the model classes, which have the methods found in the yaml file. 

After doing all this, the method(s) must be generated in the Post model class.
Since it is unclear which content the generated custom method should contain, because it is up to the user of the [Blueprint](https://blueprint.laravelshift.com/) package what statements should be provided, the shell of the method could just be placed like shown below.
This could make blueprint even cooler than it already is.

_draft of method_
```php
public function myCustomMethod(){
    //TODO: add your custom logic or create statements for it to be generated
}
```

Apart from above, it might be enough te create a method just like the swapGenerator method, but then for lexers `SwapLexer()` so the ModelLexer can be swapped with a custom ModelLexer.

**Comment by jasonmccreary** [comment]
The goal of Blueprint is _rapid code generation_. It does some by leveraging Laravel conventions so you don't have to write configuration files or builders. Said another way, generating _everything_ is not Blueprint's goal. It gives you the basics, and then gets out of the way for the developer to get to work.

With that said, I don't see the benefit in Blueprint generating empty method stubs. Keystroke for keystroke, it saves less than 20 characters.

I am considering a `meta` syntax in v2. Something Blueprint would parse and would make the syntax extendable for these types of things.
