### ISSUE TITLE
noContent responses still get status code 200 added

### ISSUE THREAD

**Issue by spaceemotion** [laravel-shift/blueprint#324]
- Laravel Version: 7.21.0
- PHP Version: 7.4.3
- Blueprint Version: 1.16.0
- Platform: Linux (Ubuntu 20)

### Issue:
(This might be intended behavior)

Generated controllers that return `response()->noContent()` seem to still get `200` as their status code added. Afaik `noContent()` should return 204 (the default). 

The code even mentions it being excluded, but the status code seems to be set incorrectly?

https://github.com/laravel-shift/blueprint/blob/e6850176f2bfd2135219afcf094939cf8b7f1823/src/Models/Statements/RespondStatement.php#L45

### draft.yaml:
```yaml
controllers:
  User:
    resource: api
```

generates:

```php
return response()->noContent(200);
```

**Comment by devmsh** [comment]
As mentioned [here](https://restfulapi.net/http-methods/#delete), it must return 204 if there is no response.

Waiting for @jasonmccreary decision and I can fix this if he agreed about the change.

**Comment by jasonmccreary** [comment]
I'd want to check this as I am confused on what outputs what. In general, there is nothing wrong with a `response()->noContent(200)`.

However, to @devmsh's comment, there may be something better depending on the context (e.g. the `destroy` response)

**Comment by devmsh** [comment]
Unfortunately, I did not get it. 

Both 200 and 204 works, but 204 seems more standardized in the restful API world.

**Comment by jasonmccreary** [comment]
Interesting. On running the draft file above, I get an error:

```sh
  Argument 1 passed to Blueprint\Generators\Statements\ResourceGenerator::visibleColumns() must be an instance of Blueprint\Models\Model, null given, called in /Users/jason/workspace/turbo-zonda/vendor/laravel-shift/blueprint/src/Generators/Statements/ResourceGenerator.php on line 105
```

**Comment by devmsh** [comment]
Just test it with v1.16.0 in a fresh Laravel installation and it works fine.

Maybe because Laravel has a default user model already?

**Comment by spaceemotion** [comment]
So I looked through the unit tests and the ControllerGeneratorTest has a few drafts that have the same behavior. The culprit seems to be this default configuration for api resource controllers:

https://github.com/laravel-shift/blueprint/blob/7c9a32ef8e46796c2ef18a21f6bbb2359690fc3c/src/Lexers/ControllerLexer.php#L126-L129

Changing it to `204` seems to do the trick.

**Comment by jasonmccreary** [comment]
@spacemotion or @devmsh, can you submit the PR to fix this. I'm still not fully understanding the issue, other than a less than desired response code.
