### ISSUE TITLE
shortcut for overwrite-migrations

### ISSUE THREAD

**Issue by cs-abdulwahab** [laravel-shift/blueprint#326]
### Synopsis:
I really like the overwrite-migrations  parameter to the    blueprint:build.
it would be more nice if there is a shortcut for that

### Proposed Syntax:
php artisan blueprint:build -o

### Expected Behavior:

same as  php artisan blueprint:build --overwrite-migrations

**Comment by devmsh** [comment]
Every time I run a blueprint command I write `bp:build` then I realize that I must run `blueprint:build` 😆 

I'm opened to add the `-o` shortcuts as well as the `bp` namespace based on the final decision

**Comment by jasonmccreary** [comment]
I am open to a shorthand, however I'm not sure I want to use `-o`. That often stands for _output_ or could mean _overwrite_ generically. Maybe `-m`?

**Comment by devmsh** [comment]
I think `-o` would be easier to remember
