### ISSUE TITLE
adding the erase parameter to the   blueprint:build

### ISSUE THREAD

**Issue by cs-abdulwahab** [laravel-shift/blueprint#327]
### Synopsis:

during development  it is quite often to erase the model and then build  
If there is a erase option along with it     

### Proposed Syntax:
php artisan blueprint:build --erase
or
php artisan blueprint:build --e

### Expected Behavior:

php artisan blueprint:erase  &&  php artisan blueprint:build

**Comment by jasonmccreary** [comment]
As discussed many times the `erase` command has many shortcomings and will likely be removed in v2. You're better off keeping this _erase_ step separate using Git or some other local process.
