### ISSUE TITLE
Allow array of rules syntax in FormRequests

### ISSUE THREAD

**Issue by spaceemotion** [laravel-shift/blueprint#334]
### Synopsis:
Instead of the normal string, separated by the pipe (|), It would be helpful to have an option to generate the array-based syntax instead.

### Proposed Syntax:
Probably a config setting, rather than something done in the yaml:

```php
<?php 

return [
	// ...
	'use_rules_array' => true, // default: false
```

This would also open up the ability to use the Rule class helpers instead of relying on just strings.

### Expected Behavior:
Generates rules in form requests like so: 

```php
return [
	'column' => ['required', 'exists:users,email'],
];
```

**Comment by jasonmccreary** [comment]
Honestly, I'm fine making this the way Blueprint generates rules. No configuration needed. 👍
