### ISSUE TITLE
Generated models should be in App\Models directory for laravel 8 applications

### ISSUE THREAD

**Issue by ajcastro** [laravel-shift/blueprint#386]
### Synopsis:
Generated models should be in `App\Models` directory for laravel 8 applications because this is the new default directory structure for models. 

But I think it's better if we create a config file like `.blueprintconfig` 
where developers can set if they want models in `App` or `App\Models` directory. In this file we can also let developers if they prefer to use the function-based factories or the new class-based factories.

**Comment by jasonmccreary** [comment]
You can configure this within your [Blueprint config](https://blueprint.laravelshift.com/docs/advanced-configuration/).
