### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by nathane** [laravel-shift/blueprint#395]
Hey, 

`PHPUnit::getAnnotations()` was recently deprecated, so https://github.com/orchestral/testbench-core/commit/fdb335ecece655de63a82c9c98c0c93fe78aa853 published a fix without the correct arguments.

PR has been submitted, it should be fixed soon.

**Comment by jasonmccreary** [comment]
Should we bump the constraint for Testbench just to ensure someone doesn't download a buggy version?

**Comment by nathane** [comment]
We can, but I don’t believe that will be necessary. The bug only affected Blueprint’s tests, not the actual library.
