### ISSUE TITLE
Extending documentation

### ISSUE THREAD

**Issue by thewebartisan7** [laravel-shift/blueprint#396]
I can't find too much info in docs regarding how to extend.
There is already somewhere or?

Thanks

**Comment by nathane** [comment]
Here's a link to the specific doc. There are examples in the `tests` folder and `"Community Addons"` section of [Extending Blueprint](https://blueprint.laravelshift.com/docs/extending-blueprint/)

**Comment by thewebartisan7** [comment]
I see that page, but it doesn't say too much, this mean that the only way is to check inside code of tests or other addons...
