### ISSUE TITLE
Config for models_namespace should default to Models since laravel 8

### ISSUE THREAD

**Issue by ajcastro** [laravel-shift/blueprint#400]
### Synopsis:
Currently the models_namespace is set to empty string. When installing new Laravel 8 applications with models namespace `App\Models` I would still need to publish the `config/blueprint.php` file then edit the `models_namespace` to `'Models'`.

### Proposed Syntax:
I proposed this should be set as default `'Models'`.

**Comment by jasonmccreary** [comment]
This has been brought up a few times and [the docs note this](https://blueprint.laravelshift.com/docs/advanced-configuration/#blueprint-configuration) as well.

It is not something I will change for version 1. Blueprint v2 will only support the latest version of Laravel and its conventions. I plan to release that for Laravel 9 (March 2021).
