### ISSUE TITLE
Custom indexes has no strings, php detects constant.

### ISSUE THREAD

**Issue by mikevandiepen** [laravel-shift/blueprint#402]
- Laravel Version: 8.x (latest)
- PHP Version: 7.4.13
- Blueprint Version: 1.19
- Platform: Mac | Windows | Linux

### Issue:
When generating custom indexes the index will be printed without `''` which causes it to fail on the migrations.

```
Schema::disableForeignKeyConstraints();
     17▕
     18▕         Schema::create('cooltable', function (Blueprint $table) {
     19▕             $table->id();
  ➜  20▕             $table->foreignId('coolcool')->constrained()->cascadeOnDelete()->index(custom_index_coolcool);
     21▕             $table->foreignId('foobar')->constrained()->cascadeOnDelete()->index(custom_index_foobar);
     22▕         });
```

### draft.yaml:
```yaml
# PLEASE PASTE THE DRAFT FILE WHICH REPRODUCES THE ISSUE HERE...
```
Draft is not required, a custom index will fail because it misses strings, therefore php detects is as a constant which is not defined.

**Comment by jasonmccreary** [comment]
@mikevandiepen, while I appreciate you feel a draft file is not required, it helps to quickly recreate the problem. Especially for these less used syntaxes.

Please include one and I'll reopen this bug.

**Comment by mikevandiepen** [comment]
I'm willing to mail it the draft file to you, but i'm not putting my system architecture out in the open. Anyhow, I've been able to circumvent this by adding `'` around the custom index name in the draft. For example; `index:'custom_index_name_foreign'`
instead of `index:custom_index_name_foreign`

**Comment by jasonmccreary** [comment]
You can just put the necessary part and anonymize it if you feel it's proprietary in some way.
