### ISSUE TITLE
TypeError: Argument 2 passed in fresh Laravel 8 during blueprint build

### ISSUE THREAD

**Issue by qontori** [laravel-shift/blueprint#406]
- Laravel Version: 8.20.1
- PHP Version: 7.4.13
- Blueprint Version: 1.20.0 
- Platform: Windows

I just started "using" Laravel and thus Blueprint - "started" because I have limited PHP knowledge too.

I have a basic Laravel install using composer on Windows (not Docker) following the Backpack getting started tutorials
https://backpackforlaravel.com/docs/4.1/getting-started-videos. I have followed the videos  with no edits, with exception to those required by Blueprint, for Laravel 8, to change models_namespace to " 'Models' " and generate_fqcn_route to "true"
https://blueprint.laravelshift.com/docs/advanced-configuration/ 

 When I run php artisan blueprint:build, the following error messages is returned

TypeError

Argument 2 passed to Blueprint\Lexers\ModelLexer::buildModel() must be of the type array, null given, called in C:\xampp\htocs\bpack\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php on line 111

at C:\xampp\htdocs\bpack\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php:124
    120
    121         return $registry;
    122     }
    123
    124     private function buildModel(string $name, array $columns)
    125     {
    126         $model = new Model($name);
    127
    128         if (isset($columns['id'])) {

  1   C:\xampp\htdocs\bpack\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php:111
      Blueprint\Lexers\ModelLexer::buildModel("Category")

  2   C:\xampp\htdocs\bpack\vendor\laravel-shift\blueprint\src\Blueprint.php:73
      Blueprint\Lexers\ModelLexer::analyze(["Atricle, Category, Tag"])

I get this error message even if I do not include backpack - ie a new Laravel 8 and blueprint only using the same draft.yml file.  Also note that the basic Laravel install does not include the file app.blade.php as per https://github.com/laravel-shift/blueprint

Thanks for any help/guidance you can provide

### draft.yaml:

models:
  Category:
  parent_id: id foreign:categories nullable
  lft: integer unsigned nullable
  rgt: integer unsigned nullable
  depth: integer unsigned nullable
  name: string
  slug: string unique
  timestamps: true
  softDeletes: true
  relationships:
    hasMany: Article
  
  Article:
    category_id: id foreign
    title: string
    slug: string unique default:''
    content: text
    image: string nullable
    status: enum:PUBLISHED, DRAFT
    date: date
    featured: boolen default:0
    timestamps: true
    softDeletes: true
    relationships: 
      belongsToMany: Tag
    
    Tag:
      name: string
      slug: string unique
      timestamps: true
      softDeletes: true
      relationships:
        belongsToMany: Article

seeders: Atricle, Category, Tag

**Comment by jasonmccreary** [comment]
This has been reported in #405.

**Comment by qontori** [comment]
I would like to check if this is expected to be working now because I pull down the latest code and check the SendStatement.php file to see if it was updated - it is.  However, I still get the same error message.

Also, I note #405 is for PHP 8, which I am on 7.4.13.

**Comment by jasonmccreary** [comment]
I believe this make occur if you are referencing a model which already exists, but you have not _traced_. Run the `blueprint:trace` command and try again. If the problem persists, I'll reopen the issue.

**Comment by IamShazaam** [comment]
dont get it why would they make a tutorial and there is an error in the beginning with no explanation...

**Comment by jasonmccreary** [comment]
@IamShazaam, not sure what you're referring to. I can successfully run `blueprint:build` using the example `draft.yaml` in the `README` with Laravel 8 + PHP 8. Not sure your issue… 🤷

**Comment by IamShazaam** [comment]
> 
> 
> @IamShazaam, not sure what you're referring to. I can successfully run `blueprint:build` using the example `draft.yaml` in the `README` with Laravel 8 + PHP 8. Not sure your issue… 🤷

I just deleted my post, the problem was that I used the migrate outside vagrant ssh. I just dont like this frameworkd, I learned to code the old way from the ground to just find out there is frameworks that do everything for you. But its just opinions, the framework works as it should.

Thanks.
