### ISSUE TITLE
Use $table->foreignIdFor(Model::class) for belongsTo and other foreign id columns

### ISSUE THREAD

**Issue by ajcastro** [laravel-shift/blueprint#411]
### Synopsis:
I think it is better to use `$table->foreignIdFor(Model::class)` for foreign key columns. Or maybe there should be a config to enable that feature.

This is better in terms when you change the datatype of the id column, you dont have to go all through the migration files to change the all instances.

I checked the docs and I did not see that this exists already so I post it here just to make sure. :)

**Comment by jasonmccreary** [comment]
While I do like this method and use it in my own application, there are mixed feelings about tying _DB layer_ migrations to _application layer_ models.

As such, this is not something I will change in v1. But maybe v2.

With that said, you are welcome to open a PR. ;)
