### ISSUE TITLE
Support of Laravel modules?

### ISSUE THREAD

**Issue by dima2306** [laravel-shift/blueprint#414]
### Synopsis:
I've [Laravel Modules](https://github.com/nWidart/laravel-modules/) package installed and seems like all of the files are generated in the root of the project as expected. But can we add Laravel modules support? For example, I have module Admin and want to generate some files within that directory Modules/Admin.

I've tried specifying a path in the yaml file like 
```yaml
models:
    Modules/Admin/Category
```

I think technically it can be done in the config by specifying the path in the command and then use it from the config, just speculating...

**Comment by jasonmccreary** [comment]
Yes, you can specify the output paths [within the config](https://github.com/laravel-shift/blueprint/blob/master/config/blueprint.php#L44) to output code wherever you like.
