### ISSUE TITLE
Draft file cannot be found

### ISSUE THREAD

**Issue by tanthammar** [laravel-shift/blueprint#421]
- Laravel Version: 8.24.0
- PHP Version: 8.0
- Blueprint Version: 1.20.2
- Platform: Mac

### Issue:
Passing a the name of draft file to the `blueprint:build` command returns: `Draft file could not be found`.

I created `models.yaml` in the root folder of my Laravel project. (Same dir as `draft.yaml`).
```
php artisan blueprint:build draft=models.yaml
```

Error:
```
Draft file could not be found: draft=models.yaml
```

also tried
```
php artisan blueprint:build draft="models.yaml"
```

**Comment by jasonmccreary** [comment]
The draft file is not an option, it's an argument. Does `blueprint:build models.yaml` work as expected?

**Comment by tanthammar** [comment]
Feeling very stupid sometimes - of course it does! :)
