### ISSUE TITLE
Morphs php annotation incorrect

### ISSUE THREAD

**Issue by tanthammar** [laravel-shift/blueprint#422]
* Laravel Version: 8.24.0
* PHP Version: 8.0
* Blueprint Version: 1.20.2
* Platform: Mac

In yaml
```yaml
obj: morphs
```

Generated annotation in Model:
```php
/**
 * @property string $obj
 */
```

Expected:
```php
/**
 * @property int $obj_id
 * @property string $obj_type
 */
```

Didn't test morphsUuid...

**Comment by jasonmccreary** [comment]
This should be a pretty straightforward fix. Why don't you take a shot at the fix in a PR. :+1:
