### ISSUE TITLE
Adding bleuprint:init as alias for blueprint:new

### ISSUE THREAD

**Issue by Wulfheart** [laravel-shift/blueprint#429]
I'd contribute this. It just keeps annoying me as I want to use it like ``git init``.

**Comment by jasonmccreary** [comment]
You could just make a system alias. But if you want to PR it, go for it.

**Comment by Wulfheart** [comment]
I use 5 different systems for laravel development. This becomes tedious quickly.

**Comment by nathane** [comment]
@Wulfheart Hey 👋, got this working for ya! Give it a test drive. 😎
