### ISSUE TITLE
Option to generate nullable rules in FormRequest

### ISSUE THREAD

**Issue by Kenifornication** [laravel-shift/blueprint#431]
### Synopsis:
The nullable fields defined in the draft could maybe also be set as nullable in the StoreRequest/UpdateRequest rules generated by Blueprint, unless there's a reason why they aren't? it's just odd to me that Blueprint generates rules for every field option except for the nullable option.

Why? because validation fails on empty/null fields. This is a fairly quick edit for the dev to fix it but I feel like it should be supported out of the box by Blueprint.

### Proposed Syntax:
No syntax change.

### Expected Behavior:
Fields defined as nullable in the draft file to be set as nullable in the Request rules as well.

**Comment by jasonmccreary** [comment]
Blueprint should generate the validation rules for any attribute you list within the `validate` statement.

If you're looking to generate these via the `resource` shorthands, then I'm open to that being added as a config option, similar to `fake_nullables`. Feel free to start a PR, otherwise, I'll may revisit this in the next live-stream.

**Comment by Kenifornication** [comment]
> If you're looking to generate these via the `resource` shorthands, then I'm open to that being added as a config option, similar to `fake_nullables`

I forgot to specify that in the OP. Yeah, I'm talking about the resource shorthand. I'm of the "generate everything then chop it down as you go"school of thought.

> Feel free to start a PR, otherwise, I'll may revisit this in the next live-stream.

Yeah sorry I'm really a PHP rookie, not yet at that "contributes to open source projects" level yet lol

Just out of curiosity, why would you make it an option and not a default behavior? is it something to do with tests?

**Comment by jasonmccreary** [comment]
The form request should be catered to the form data. I don't think it's always the case that all model attributes are being sent for the `store` and `update` requests.

So it's a catch either way, either those that are sending all model attributes add the `nullable` fields, or those that aren't delete the `nullable` fields. Neither is a good experience. So I think an options that explicitly enables generate them at least provides an _opt-in_ approach.
