### ISSUE TITLE
Create a model based on a sql view

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#443]
### Synopsis:

https://laracasts.com/discuss/channels/laravel/blueprint-extension

### Proposed Syntax:
```
Models:
    Model: View
        sql: raw sql to create the view
```

### Expected Behavior:
Create the migration and the  model

**Comment by jasonmccreary** [comment]
This will probably be best as an extension or even it's own package.

**Comment by sr57** [comment]
Hi @jasonmccreary 
Thanks for reply.
Did you read my post on Laracast, I need some guidance to do it well.
