### ISSUE TITLE
Create a JSON schema for IDE suggestion/validation/completion

### ISSUE THREAD

**Issue by henriquecm** [laravel-shift/blueprint#444]
### Synopsis:
Having a json schema would allow IDEs to give suggestions while editing the yaml file and could also validate it.
This file could come with the package or hosted online.
I know that at least PHPStorm has support for this, and VSCode has a extension.

**Comment by jasonmccreary** [comment]
This would be really cool. I'm not familiar with creating these. Do you have any references you could link or experience creating these yourself?

**Comment by henriquecm** [comment]
I'll try to make a json schema with what I know, but I am new to laravel-blueprint

**Comment by jasonmccreary** [comment]
Totally fine. Understanding the schema is what will help. From there I, or someone in the community, could fill in the blanks.

**Comment by jasonmccreary** [comment]
Since there are no updates on this. I am closing. If you or a future reader wants to submit a PR adding this, I will gladly merge it.
