### ISSUE TITLE
softDeletes not working, causes error at the time of generating code

### ISSUE THREAD

**Issue by noorcs** [laravel-shift/blueprint#45]
![Screenshot (436)](https://user-images.githubusercontent.com/12681020/71781379-ebeba680-2fef-11ea-8fc6-428300e0f089.png)

Everything works fine for me, except when I add softDeletes to yaml file, then it shows the error as displayed in the screenshot.

![Screenshot (437)](https://user-images.githubusercontent.com/12681020/71781402-5b619600-2ff0-11ea-8182-bfe052aefc98.png)

I don't know if I not following the syntax of blueprint or what?

**Comment by noorcs** [comment]
OK so I just digged into the blueprint source code. And finally found out that it was all lower case  `softdeletes` and I assigned value `true` to it. This way it worked. I had followed all the documentation and in this issue #39  for blueprint where I got the `softDeletes` word. So I had just followed that. 

Now I got it with success. Here is my yaml file:

    models:
        Salesperson:
            name: string:255
            f_name: string:255
            dob: date
            address: string:400
            softdeletes: true

    controllers:
       Salesperson:
          index:
            query: all
            render: salesperson.index with:salespeople
    
        create:
            render: salesperson.create

        store:
            validate: name, f_name
            save: salesperson
            flash: salesperson.name
            redirect: salesperson.index
    
        show:
            render: salesperson.show with:salesperson

        edit:
            render: salesperson.edit with:salesperson

        update:
            validate: name, f_name
            update: salesperson
            flash: salesperson.name
            redirect: salesperson.index

        destroy:
            delete: salesperson
            redirect: salesperson.index

and here is the screenshot after execution:
![Screenshot (438)](https://user-images.githubusercontent.com/12681020/71782158-e181da80-2ff8-11ea-8208-106eb0f0ee5d.png)

**Comment by jasonmccreary** [comment]
Yes, Blueprint uses some _shorthands_ which are technically invalid YAML syntax. These were for developer convenience.

To enable soft deletes for a model, you can simply write: `softDeletes` or `softdeletes`, or to write valid YAML: `softDeletes: true` or `softdeletes: true`
