### ISSUE TITLE
redirect()->with('message', ...)

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#452]
### Synopsis:
cf examples here : https://www.itsolutionstuff.com/post/laravel-7-flash-message-exampleexample.html
If it's possible, let me know how and I'll do a PR in the doc.
If not and if this should be valuable and want me to propose a solution, just guide me where/how to better do this update.
https://www.itsolutionstuff.com/post/laravel-7-flash-message-exampleexample.html
### Proposed Syntax:
redirect: post.index $tag:msg
ex : redirect: post.index $warning:'your pwd should be longer.'

### Expected Behavior:
https://www.itsolutionstuff.com/post/laravel-7-flash-message-exampleexample.html

**Comment by nathane** [comment]
Have you tried the `flash` controller statement?

https://blueprint.laravelshift.com/docs/controller-statements/

**Comment by sr57** [comment]
Hi @nathane 

Yes but without success, can you give an example of yaml syntax to generate my example?

**Comment by nathane** [comment]
@sr57, inside of [`tests/fixtures/drafts`](https://github.com/laravel-shift/blueprint/tree/master/tests/fixtures/drafts) you will find example draft files. here is one using the `flash` statement.

https://github.com/laravel-shift/blueprint/blob/9865ae885b2df5b62421641579b137077e40607c/tests/fixtures/drafts/readme-example.yaml#L1-L21

**Comment by sr57** [comment]
Thanks @nathane for your reply but it does not answer to the question, the flash acts an a defined variable.

**Comment by jasonmccreary** [comment]
This syntax is not supported. You may only reference variables, not create new ones.

A reminder Blueprint is a rapid code generation tool, not a 1:1 replacement for writing Laravel.
