### ISSUE TITLE
Post build script

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#457]
### Synopsis:
call a post_build empty/user customizable function at the end of build command.

### Proposed Syntax:
Just :
 - define the name of post build script in the doc.
 - have access to the config tree in order to be able to make changes depending of the config .yaml file. 

### Usage:
- Small adjustments (add standard personal routes, ... ) 
- Some can be 'standard' of them could be shared like the one suggested in the next issue.

**Comment by jasonmccreary** [comment]
This can be achieved with a custom "Generator". Any user registered generator would be run _after_ all the core generators.

**Comment by nathane** [comment]
Docs: [https://blueprint.laravelshift.com/docs/extending-blueprint/](https://blueprint.laravelshift.com/docs/extending-blueprint/)

**Comment by sr57** [comment]
Hi @jasonmccreary @nathane 

Ok with your solution, we can also create a Laravel command to excecute blueprint build and other stuffs in a row both even both solutions are not difficult, my proposition was to have st immediate.

That said, my first intention was to update the doc (PR) with your answers but it is rather complete and updating a doc is a bottomless pit. So I thought of writing this FAQ, if it can be useful to others, that's great.

https://github.com/sr57/laravel-blueprint-faq
