### ISSUE TITLE
No duplicate route

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#458]
### Synopsis:
As written in the doc erase command is not perfect, nevertheless it's a useful command during tests , the main pb is that each new build creates duplicate routes.
Do not write routes that already exist. 

### Proposed Syntax:
None.

### Expected Behavior:
No duplicate routes.

Proposes solutions:
1) test if exist before each new route generation
2) use Post build script (see previous issue) tu remove duplicate routes.

**Comment by jasonmccreary** [comment]
Similar to #540, the amount of tracking/code to do this properly is not worth the effort in my opinion. I will gladly accept a PR which addresses this issue.

For me, I wouldn't even use Blueprint to "undo" a command, I'd use Git. For example, `git reset --hard` or, more surgically, `git checkout -- routes/web.php`
