### ISSUE TITLE
Pre generator script

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#465]
### Synopsis:

Launch a user defined script at the beginning of the command blueprint:build

Ability de review draft.yaml (no s at the end of a model name, ...) for existing syntax and user defined ones (sql views creation, ...)

### Proposed Syntax:
None except a standard name for the script to be executed if exists.

**Comment by jasonmccreary** [comment]
I think you could make your own command that does this, then calls `blueprint:build`.
