### ISSUE TITLE
Class names getting cut-off in factory

### ISSUE THREAD

**Issue by RyanPriceDotCa** [laravel-shift/blueprint#47]
The generator that attaches relationships to models us cutting off the last 3 letters of the class.  Traced it to this PR: https://github.com/laravel-shift/blueprint/pull/36

Issue is on this line:
https://github.com/laravel-shift/blueprint/blob/3974db7ffff8c647ce105076a5e2f5ef150e3c16/src/Generators/FactoryGenerator.php#L66

It results in code that looks something like this (you can see each is missing characters at the end):

```
        'department' => factory(\App\Departm::class),
        'supervisor' => factory(\App\Supervi::class),
        'comments' => $faker->,
        'organization' => factory(\App\Organizat::class),
        'campus' => factory(\App\Cam::class),
        'building' => factory(\App\Build::class),
```

I wanted to post it as an issue to make sure I wasn't doing something wrong.  I can't see why the column name is being cut here.

**Comment by jasonmccreary** [comment]
Interesting, there should be tests for this.

I'll get this patched tomorrow as I plan to review the open issues. Unless, of course, you'd like to take a stab.

**Comment by jasonmccreary** [comment]
@RyanPriceDotCa, can you post your _draft_ file that results in this?

**Comment by jasonmccreary** [comment]
Okay, I see what's happening here and realize why this was an interesting "bug" and not more widespread.

The Laravel conventions for related models is to suffix them with `_id`, which you're not doing. Blueprint expects and generates conventional code.

With that said, given the ease of the change, I made it and added tests.

**Comment by RyanPriceDotCa** [comment]
Ah, that makes sense.  I will keep in mind that best-practice moving forward and am happy I didn't just suggest a patch that dropped that step.
