### ISSUE TITLE
TestGeneraor - call to a member function column() on null - line 252

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#474]
Laravel Version: 8.33.1
PHP Version: 7.4.3
Blueprint Version: 1.23
Platform: Linux

### Issue:
TestGeneraor - call to a member function column() on null - line 252

### Correction
line 252 : if ( ! is_null($local_model) ) {

### draft.yaml:
no model

### use case
To create sql view we need to have all the tables created (included pivot) so to divide draft.yaml in 2 or more parts. First one with the models and second one with the remaining objects. The error occurs when executing build on the second config file taht contains no model.

**Comment by jasonmccreary** [comment]
@sr57, please provide a sample `draft.yaml` file to recreate the issue.

**Comment by ghostwriter** [comment]
@sr57 I've submitted a pr #477 to fix this. 

If you're still having problems feel free to provide a sample `draft.yaml`, as JMac previously stated,  so we can properly test and fix the issue. :)

**Comment by jasonmccreary** [comment]
@sr57, can you set your dependency to `dev-master` and confirm the latest patch resolves this issue?

**Comment by sr57** [comment]
Hi @jasonmccreary 
It's Ok.
Thanks for your correction.
