### ISSUE TITLE
Have access to all models (included those in cache)

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#475]
### Synopsis:
None

### Proposed Syntax:
change models function in Tree.php to return $this->models rather than $this->tree['models']
or
add a new function

### Use Case
See previous issue #474  , when draft.yaml is splitted in two, the first one containing no model.

**Comment by jasonmccreary** [comment]
As noted before, do not open multiple issues referencing a previous issue. Please open a single issue using the proper template for a bug or issue a PR directly with the fix.
