### ISSUE TITLE
Do not use FQCN for model relationships

### ISSUE THREAD

**Issue by ajcastro** [laravel-shift/blueprint#484]
Currently, the generated relationships use FQCN for the model. Usually, the models are in the same namespace like `App\Models\` so I would like to have an option to remove the namespace in the model. 

Current Behavior:
```php
class User extends Model
{
    public function company()
    {
        return $this->belongsTo(\App\Models\Company::class);
    }
}
```

Suggested:
```php
class User extends Model
{
    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}
```

**Comment by jasonmccreary** [comment]
We should have the namespace for the current model, so determining a prefix match against related models should be straightforward. However, there's always a tricky part.

I'll tag this as an enhancement. Probably won't get to it for a while though. So feel free to open a PR. 👍
