### ISSUE TITLE
The softDeletes should be put after the timestamps 

### ISSUE THREAD

**Issue by ajcastro** [laravel-shift/blueprint#485]
- Laravel Version: 8.38.0
- PHP Version: 7.4.16
- Blueprint Version: v1.24.1
- Platform: Windows 

### Issue:

Currently, when I have softDeletes in the yaml, the softDeletes method is put first before the timestamps. Usually 
softDeletes should be put after the timestamps.

Current behavior:

```php
 Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->softDeletes(); // this should be put after the timestamps
            $table->timestamps();
        });
```

Expected behavior:

```php
 Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
            $table->softDeletes(); // this should be put after the timestamps
        });
```

I already tried explicitly putting timestamps and softDeletes order in the yaml but still the same output:
```yaml
models:
  User:
    name: string
    timestamps
    softDeletes

```

**Comment by jasonmccreary** [comment]
I don't think Blueprint should always put it last. However, it should respect the explicit order from the draft file.

**Comment by ajcastro** [comment]
Also maybe it is a good default that the softDeletes is put at last.

**Comment by jasonmccreary** [comment]
The new default will be to put it in the same order as the draft file. It's the most obvious.
