### ISSUE TITLE
Solution for Laravel 8 regarding Models direction.

### ISSUE THREAD

**Issue by mansourcodes** [laravel-shift/blueprint#489]
## Solution for Laravel 8 regarding Models direction.

 Generate Models inside a Models directory starting with Laravel 8  we recommend making the config as:

```
-    'models_namespace' => '',
+    'models_namespace' => substr(app()::VERSION, 0, 1) >= 8 ? 'Models' : '',

      // And maybe
-    'generate_fqcn_route' => false,
+    'generate_fqcn_route' => substr(app()::VERSION, 0, 1) >= 8 ? true : false,
```

**Comment by jasonmccreary** [comment]
I'm probably going to make Blueprint use Laravel 8 only soon. So this will be a non-issue.
