### ISSUE TITLE
Why store & update does not use factories ?

### ISSUE THREAD

**Issue by YannikFirre** [laravel-shift/blueprint#497]
Hello,

### Synopsis:
Question or improvement about test generation for the store and update methods.
Related to https://github.com/fidum/laravel-blueprint-pestphp-addon/issues/27

### Proposed Syntax:
Use factory for the data sent in the request as you already do for relationships.

Actually : 
https://github.com/laravel-shift/blueprint/blob/67cfc6b01c50545a5f050fa4f88633993e759f21/tests/fixtures/tests/readme-example.php#L55

```
        $title = $this->faker->sentence(4);
        $content = $this->faker->paragraphs(3, true);
        $author = factory(User::class)->create();

        $response = $this->post(route('post.store'), [
            'title' => $title,
            'content' => $content,
            'author_id' => $author->id,
        ]);

```

Changed by : 
```
       $postToCreate = factory(Post::class)->make();

        $title = $postToCreate->title;
        $content = $postToCreate->content;
        $author = factory(User::class)->create();

        $response = $this->post(route('post.store'), [
            'title' => $title,
            'content' => $content,
            'author_id' => $author->id,
        ]);
```
### Use case:
Currently if I change the generation of data in the factory, I have to update the tests as well

Perhaps there is a good reason for the current behaviour ?

Thank you in advance for your reply

**Comment by jasonmccreary** [comment]
This makes the test case more explicit. It's discussed ad nauseam in #220.
