### ISSUE TITLE
Feature Request: Remember files

### ISSUE THREAD

**Issue by vittorioe** [laravel-shift/blueprint#50]
I think it would be amazing if a kind of manifest file would be generated in the app store where the generated files of the blueprint are documented.
Later, if we regenerate the blueprint, we override all the files which are having the same hash sums like before, also we should scan the web.php for the occurrence of the lines we want to generate and then we should skip the lines in a given case.

**Comment by jasonmccreary** [comment]
Blueprint uses a `.blueprint` file that powers an `erase` command, and remembers model definitions for future runs. You are also welcome to save/share draft files.

Between those two options, what feature is needed?

**Comment by jasonmccreary** [comment]
Closing without additional information.
