### ISSUE TITLE
Mailable should generate its template file

### ISSUE THREAD

**Issue by lintaba** [laravel-shift/blueprint#506]
### Synopsis:
Currently a mailable generates template with this:
```php
        return $this->view('view.name');
```
I think it could be useful to generate the relevant template file too.

### Proposed Syntax:
currently existing syntax could remain unchanged, or can be extended with a parameter, like `view:email.reviewPost`
```yaml
      send: ReviewPost to:post.author with:post
```

### Expected Behavior:
- add an optional parameter to `send` statement (view). default value could be `email.{mail}`.
- generate a view for this view path, if not exists.
- pass the notification's parameters to the view, and maybe have a parameter hint at the begining of the view's file

**Comment by jasonmccreary** [comment]
I'd be open to this if you'd like to start a PR. The only change I would make is a snake or kebab case template name (e.g. `review-post.blade.php`)

**Comment by lintaba** [comment]
snake/kebab is on the user. I made it to be fully optional and backward compatible, so you have to provide the view:foo-bar / view:fooBar.
a decision that i made (which can be changed) is to prefix the view name with `email.` automatically, so its just `view:reviewPost`, and it creates the file as `resources/views/emails/reviewPost.blade.php`
