### ISSUE TITLE
make views folder for match name convention 

### ISSUE THREAD

**Issue by spham** [laravel-shift/blueprint#508]
### Synopsis:
the name forder with singular
ie: post/index.blade.php

### Proposed Syntax:

so it should store with plural name, if we user conventin for best practice

### Expected Behavior:

```
posts/index.blade.php
posts/create.blade.php
...
```

**Comment by jasonmccreary** [comment]
There is no _official_ naming conventions. Blueprint should follow whatever name you use when referencing your views or the controller prefix.

**Comment by spham** [comment]
Hi, what's new on 2023 ?

**Comment by jasonmccreary** [comment]
Nothing.
