### ISSUE TITLE
Livewire and Screencasts 

### ISSUE THREAD

**Issue by silicahd** [laravel-shift/blueprint#509]
Honestly it would be amazing to see some livewire generation. However you should also create something like livewire did with screencasts and allow people to pay for your pro videos. I know I would be one of them.   https://laravel-livewire.com/

**Comment by jasonmccreary** [comment]
This is probably not something Blueprint will do directly. However, you can create an [add-on](https://blueprint.laravelshift.com/docs/extending-blueprint/).
