### ISSUE TITLE
Idea: Would be great if it form boilerplate too?

### ISSUE THREAD

**Issue by DanJamesMills** [laravel-shift/blueprint#51]
Hi,

Great package love it, It would be great if it could also generate form boilerplate too.

Has anyone got any interest in this?

**Comment by jasonmccreary** [comment]
Probably not in core. Too many nuances between the UI to get it just right.

Could be something someone else adds as I have made Blueprint extendable. So someone could easily create and register a `FormBuilderGenerator` that uses the model definitions to output code.
