### ISSUE TITLE
Ignore parameters, tags, sections not used by blueprint

### ISSUE THREAD

**Issue by jvallef** [laravel-shift/blueprint#513]
Hi,

Ignore any parameter in fields, in sections or new sections that Blueprint don't use

No proposed syntax, not needed, simply ignore it.

Probably you already implemented in that way, running a quick couple of tests seems it works in that way. Simply keep that in the future, please.

The purpose is to use draft.yaml to be called for other processes for example to generate views or tables, adding extra parameters or sections.

Thanks for your great work.

**Comment by jasonmccreary** [comment]
I'll need an example of a syntax which is Blueprint compatible but has extra data.
