### ISSUE TITLE
The project would be nice to have a module option

### ISSUE THREAD

**Issue by silicahd** [laravel-shift/blueprint#515]
I use these other project nwidart for some time. It is nice that it splits all the modules in there own folder. It would be nice to have something like this in blueprint. This way you do not end up with a bunch of files in the same folders for each module. 

[](https://nwidart.com/laravel-modules/v6/introduction)](https://nwidart.com/laravel-modules/v6/introduction)

**Comment by jasonmccreary** [comment]
You may configure Blueprint to output components in other directories. However, specific support for that package is not supported.
