### ISSUE TITLE
Update codebase to use newer model namespace/folder structure: app/Models/Foo.php

### ISSUE THREAD

**Issue by benjam-es** [laravel-shift/blueprint#518]
### Synopsis:
It would make it simpler to contribute if laravel defaults are up to date. With limited codebase knowledge I tried to create a pull request whilst using (copy and pasting) existing tests. It wasn't immediately clear that blueprint does work correctly in the wild, to produce models in the expected namespace, but test cases force change the namespace setting to keep older written tests working

### Proposed Syntax:
For example, change various model instances as follows

``` app/User.php```

to 

``` app/Models/User.php```

### Expected Behavior:
New contributors may naturally use the newest namespace/folder structure, so this would reduce friction

**Comment by jasonmccreary** [comment]
Agreed. This is what v2 was for (to align with the latest conventions). I'll take a look at this in my next live stream. In the meantime, feel free to open a PR with the model path defaulting to `app/Models`.
