### ISSUE TITLE
Consider v2 using blade templates, and publishable stubs like Laravel

### ISSUE THREAD

**Issue by benjam-es** [laravel-shift/blueprint#519]
### Synopsis:
Using a blade template would save on a lot of 'string replace' code. It may also simplify each section within models/controllers. A further benefit of this would make a lot of things flexible for the end users. i.e. I was a pull request discussing plural routes. In this case, it would be achieved by adding .'s' somewhere in the blade template for routes

### Proposed Syntax:

We could replace the old syntax

```
    protected function populateStub(string $stub, Model $model)
    {
        $stub = str_replace('{{ namespace }}', $model->fullyQualifiedNamespace(), $stub);
        $stub = str_replace(PHP_EOL . 'class {{ class }}', $this->buildClassPhpDoc($model) . PHP_EOL . 'class {{ class }}', $stub);
        $stub = str_replace('{{ class }}', $model->name(), $stub);

        $body = $this->buildProperties($model);
        $body .= PHP_EOL . PHP_EOL;
        $body .= $this->buildRelationships($model);

        $stub = str_replace('use HasFactory;', 'use HasFactory;' . PHP_EOL . PHP_EOL . '    ' . trim($body), $stub);

        $stub = $this->addTraits($model, $stub);

        return $stub;
    }
```

with something along the lines of

```
    protected function populateStub(string $stub, Model $model)
    {
        return view('stubs/model', compact($model))->render();
    }
```
This would then just have subviews with foreach loops for traits, use statements, methods etc from the passed in model. Allowing for any complex customisations, where users and use if statements, pulling in config() etc.

### Expected Behavior:
Reduce code, clean up a lot of noise, clean syntax, highly adaptable, leverage the framework.

**Comment by jasonmccreary** [comment]
I'm open to this. Not something I'd refactor on my own. But if someone wanted to open a PR with an example of one of the generators using Blade, I'd consider it.

**Comment by benjam-es** [comment]
After a few pull requests, and understanding the package better, I think we could probably just lose this as an issue? 

I still see the benefit in being able to use blade, and the logic within 'views' to remove a lot of string replace etc. However, this is likely to lose the simplicity of the stubs, and make it a bigger task for the user who wants to customise stubs. The simple stubs are how laravel handles it also, so it would be moving away from that.

Happy to close this, or if you do see any value in it, I would also be happy to code up a sample to review.(?)

**Comment by jasonmccreary** [comment]
I'd still like to see a convergence of the Blueprint stubs with the Laravel stubs. Ideally, Blueprint doesn't have its own.

**Comment by benjam-es** [comment]
Are you referring to making blueprint start using laravel stubs?. I think that may be different to this original issue I raised. 

This issue was suggesting that the package have a full blade view

**Comment by jasonmccreary** [comment]
Gotcha. Closing.
