### ISSUE TITLE
Add Foreign key column to Relationship in Model

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-shift/blueprint#523]
### Synopsis:

While creating a model columns with custom column name `(doesn't follow laravel convention)`. It doesn't add column name to relation.

So let's say i have following Yaml 

**Sample 1**
```
models:
  Post:
    id
    content: text nullable
    created_by_id: id nullable bigInteger unsigned foreign:users.id
    timestamps
    softDeletes
```

### Expected Behavior:

While generating Model relations It can automatically add `created_by_id` as second argument. And 

```
public function createdBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class,"created_by_id");
    }
```

**Sample 2**
```
models:
  Post:
    id
    content: text nullable
    created_by_id: id nullable bigInteger unsigned foreign:users.user_id
    timestamps
    softDeletes
```

### Expected Behavior:

While generating Model relations It can automatically add `created_by_id` and  as second argument as `user_id`

```
public function createdBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class,"created_by_id","user_id");
    }
```

**Comment by jasonmccreary** [comment]
Feel free to submit a PR with the fix. Otherwise, I will patch this in a [future live stream](https://www.youtube.com/watch?v=xCHi-JswDgI&list=PLmwAMIdrAmK5q0c0JUqzW3u9tb0AqW95w&index=33).

**Comment by jasonmccreary** [comment]
Finally got around to testing this, it seems to behave as expected. However, let me know if not.
