### ISSUE TITLE
Include pest for improved speed and CLI output

### ISSUE THREAD

**Issue by benjam-es** [laravel-shift/blueprint#525]
### Synopsis:
Benefit from parallel testing and improved CLI user interface by offering pest. Composer script to run tests in either phpunit or pest

### Proposed Syntax:
n/a

### Expected Behavior:
Testing improvements

**Comment by jasonmccreary** [comment]
I'm glad to add an option to generate Pest tests within Blueprint.

I do believe there is a community add-on which does this already though. Maybe they could open a PR. 😅

**Comment by benjam-es** [comment]
@jasonmccreary this is just for running the tests within Blueprint

**Comment by jasonmccreary** [comment]
Thanks, but Blueprint uses PHPUnit, and I'm fine with their runner.
