### ISSUE TITLE
Extract common functionality into an abstract class generator

### ISSUE THREAD

**Issue by benjam-es** [laravel-shift/blueprint#527]
### Synopsis:
Extract common functionality into an abstract/base class generator to clean up and simplify code within all generators

### Proposed Syntax:
Some functions will need editing to 'standardise' them before extracting them out such as getPath, buildImports etc. Use blueprint model contract so that we can type hint that in place of the passed blueprint models within common functions.

### Expected Behavior:
Cleaner code, easier to adapt, clean up repeated code

Providing further future benefits
 - Give the model generator access to the buildImports method to reduce the usage of fully qualified class names throughout
 - Cleaner base for a potential switch to the use of blade
 - Improve handling imports in general
   - Allowing new 'default' / configurable default imports per class
   - Allowing for other functionality such as configurable import sorting strategy

Im working on a pull request for this at the moment, so might be worth me keeping a live branch of it for you to look over rather than a large pull request?

**Comment by jasonmccreary** [comment]
@benjam-es, I'm open to cleaning this up. There are several methods which are "copied" between the generators.

However, I am not looking to create multiple class inheritance. Said another way, any PR would need to actually reduce code. Not add a bunch more classes and move the code.

**Comment by benjam-es** [comment]
@jasonmccreary I won't put in a pull request on this one unless requested, as its quite a lot of changes, and some of it may be too opinionated, and/or not how you want things.

Here is a look at reducing around 300+ lines [https://github.com/laravel-shift/blueprint/compare/master...benjam-es:enhancement/refactoring](https://github.com/laravel-shift/blueprint/compare/master...benjam-es:enhancement/refactoring)

It might offer up some suggestions for you. Let me know if you would like me to make it a PR, or sub sections of it

The main bulk of what is done it to separate out some common functionality into an abstract class. Ive also moved some trait/import functionality into separate concerns so it can be reused as needed, with a few other tweaks.

Added benefit of this, is also that models now have access to the addTrait and addImport functionality... this could easily be used for cleaning up FQCN throughout classes

I did start to get into refactoring more of the getPath methods and making models for seeders/factories to make use of just one getPath method, but it started to become a little convoluted. There is also potential for refactoring the output method where some are very similar, but again, this branch has a lot of changes already.

**Comment by jasonmccreary** [comment]
@benjam-es, I am open to this. I do think it's a good streamline. Feel free to open a PR.

A few points I'll make early on though:

- Please mind the code style (Laravel)
- Not all classes use the same properties. I understand consolidating them. I wonder if the individual traits should be added to the classes that use them instead of on the abstract class.
- I'm reluctant to add any more interfaces. I really only added the others for extendability. So let's make sure this one fits.

🚀

**Comment by benjam-es** [comment]
I opted for using the traits rather than methods on the abstract class directly so they could be used in other places if needed. Went with an abstract/base class, as there were other repeated blocks of code which were also worth keeping in one place, such as the constructor, file initialisation, 'type' getting - reduced to single class property.

i'll make a pull request, and make changes where needed or where you have a different preference to how i've done things (hopefully with some guidance on code style you mention?)

**Comment by benjam-es** [comment]
closed by #532
