### ISSUE TITLE
Stubs/config publish 'improvement'

### ISSUE THREAD

**Issue by benjam-es** [laravel-shift/blueprint#528]
### Synopsis:
It looks like the current method of publishing the 'stubs' files, is to use ```php artisan vendor:publish --tag=...``` which is usable. I think there may be room for improvement. Similarly it might be useful to complete multiple steps in one line (new, publish stubs, publish config)

### Proposed Syntax:
Use a new command for config publishing, which then simply calls the vendor:publish

```php artisan blueprint:stubs```

The ```blueprint:new``` command could have a couple of flags like so:

```blueprint:new --config```
```blueprint:new --stubs```
```blueprint:new --cs``` (or shorthand)

### Expected Behavior:

1. Specific command for publishing (similar laravel)
2. Streamline 3 steps into 1 step for those wanting to start a new draft file, publish stubs and publish config

**Comment by jasonmccreary** [comment]
I'm open to this.

**Note:** in the future if you already have code, just open the PR. No need for the issue, then the PR.

**Comment by benjam-es** [comment]
Noted.

Sorry, just created issues as an idea comes to mind. Been binge watching some of the blueprint videos since I came across it.
