### ISSUE TITLE
Pivot Table supported

### ISSUE THREAD

**Issue by Wulfheart** [laravel-shift/blueprint#54]
Are pivot tables supported yet?

**Comment by jasonmccreary** [comment]
Can you provide an example.

**Comment by Wulfheart** [comment]
```
   public function buildings() {
        return $this->belongsToMany('App\Building', 'village_building', 'village_id', 'building_id')->withPivot('level');
    }
```

[Search here for more examples with pivot.](https://laravel.com/docs/6.x/eloquent-relationships#defining-custom-intermediate-table-models)

**Comment by jasonmccreary** [comment]
At this time, Blueprint does not generate relationships beyond `belongsTo`. #4 is already an open for this.

Again, if you would like to suggest a syntax for this, I am taking recommendations.
