### ISSUE TITLE
Enable Blueprint to be able to undo file updates.

### ISSUE THREAD

**Issue by alagiesellu** [laravel-shift/blueprint#540]
### Synopsis:
When blueprint updates a file like the web.php route file, the rollback command does not undo the update action.

### Proposed Syntax:
So what if blueprint will always commend on any file it updates, comments will enable blueprint to know the lines of code it has added to the file so that when you roll back a build, blueprint can the lines of code it wrote and then remove them.

**Comment by jasonmccreary** [comment]
This is a known limitation of Blueprint. The amount of tracking/code to do this properly is not worth the effort in my opinion. I will gladly access a PR which addresses this issue.

For me, I wouldn't even use Blueprint to "undo" a mistake, I'd use `git`. For example, `git reset --hard` or, more surgically, `git checkout -- routes/web.php`.
