### ISSUE TITLE
laravel9 install issue

### ISSUE THREAD

**Issue by spham** [laravel-shift/blueprint#541]
hi
just for this in fresh laravl 9
```

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-shift/blueprint ^2.1 -> satisfiable by laravel-shift/blueprint[v2.1.0].
    - laravel-shift/blueprint v2.1.0 requires illuminate/console ^8.0 -> found illuminate/console[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
```

**Comment by tabacitu** [comment]
L9 support is coming 😀 

@laravel-shift just pushed a BIG commit 12 hours ago, adding L9 support - https://github.com/laravel-shift/blueprint/commit/a612da5d194ccb213d434241e5fd8ea18bb2c62b but it hasn't been tagged/released yet.

**Comment by Robovize** [comment]
I have the same issue but with Laravel  8.83.4

**Comment by digitall-it** [comment]
I installed the version 2.4 on Laravel 9.11 without any problems.

**Comment by tabacitu** [comment]
Yup, can also confirm it's working. L9 support was launched on Feb 13th 2022, in [v2.3.0](https://github.com/laravel-shift/blueprint/releases/tag/v2.3.0) 🎉 

This issue should be closed.
