### ISSUE TITLE
The method 'assertDeleted' does not exists, use 'assertModelMissing' instead

### ISSUE THREAD

**Issue by cjfloss** [laravel-shift/blueprint#547]
The method assertDeleted was removed in Laravel 9 https://github.com/laravel/framework/pull/39661

https://github.com/laravel-shift/blueprint/blob/a612da5d194ccb213d434241e5fd8ea18bb2c62b/src/Generators/TestGenerator.php#L422

**Comment by jasonmccreary** [comment]
Good catch. Could you make a quick PR for this?

**Comment by dmason30** [comment]
@jasonmccreary Just fixed this on the pest extension 😄 

Submitted PR https://github.com/laravel-shift/blueprint/pull/554

**Comment by jasonmccreary** [comment]
@dmason30, cool. In the future, feel free to put everything in the PR to save yourself time opening issues/etc.

**Comment by dmason30** [comment]
@jasonmccreary confused 🤣 I didn’t create this issue 🤔 ?
