### ISSUE TITLE
Laravel 9, Scout fullText index

### ISSUE THREAD

**Issue by tanthammar** [laravel-shift/blueprint#548]
### Synopsis:
Laravel 9 comes with a database driver for Laravel Scout. It would be great if we could add support for `fullText` indexes which is one of the recommended data types.

### Proposed Syntax:

`foo: fullText` should output `$table->fullText('foo')` in migrations

### Expected Behavior:

I hoped it was enough to add `'fullText' => 'fullText', ` to the `ModelLexer->dataTypes` array, but it didn't do it :)

**Comment by jasonmccreary** [comment]
I like it. Feel free to take a stab at a PR.
