### ISSUE TITLE
Error in installing Blueprint with Laravel 8

### ISSUE THREAD

**Issue by UnimartTeam** [laravel-shift/blueprint#552]
- Laravel Version: 8.75
- PHP Version: 8.0
- Blueprint Version: 2.3
- Platform: Windows 

### Issue:

  Problem 1
    - Root composer.json requires laravel-shift/blueprint ^2.3 -> satisfiable by laravel-shift/blueprint[v2.3.0].
    - laravel-shift/blueprint v2.3.0 requires illuminate/console ^9.0 -> found illuminate/console[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by jasonmccreary** [comment]
Blueprint always supports the latest version of Laravel.

Laravel 8 support ended with 2.2. You may lock that version to use Blueprint with Laravel 8, but it will not receive additional features or bug fixes.
