### ISSUE TITLE
Install 2.3 fails on Illuminate/Console ^9.0

### ISSUE THREAD

**Issue by CharlieNH** [laravel-shift/blueprint#555]
- Laravel Version: 8.83.4
- PHP Version: 7.4.19
- Blueprint Version: 2.3.0
- Platform: Windows, Laragon

### Issue:
In a clean new Laravel project I installed Backpack and Backpack Generator with no problem.
When I tried to install Blueprint 2.3 it failed:

composer require --dev laravel-shift/blueprint
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^2.3 for laravel-shift/blueprint
./composer.json has been updated
Running composer update laravel-shift/blueprint
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-shift/blueprint ^2.3 -> satisfiable by laravel-shift/blueprint[v2.3.0].
    - laravel-shift/blueprint v2.3.0 requires illuminate/console ^9.0 -> found illuminate/console[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

I tried "composer update" (which _did_ mention Illuminate ... see below)

Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: backpack/crud
Discovered Package: backpack/generators
Discovered Package: creativeorange/gravatar
Discovered Package: digitallyhappy/assets
Discovered Package: facade/ignition
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prologue/alerts
Package manifest generated successfully.
81 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force
No publishable resources for tag [laravel-assets].
Publishing complete.

But the composer update didn't change the symptom when I tried again to install Blueprint 2.3.

On a hunch, I tried installing 2.2 and it worked!

composer require --dev laravel-shift/blueprint:^2.2
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update laravel-shift/blueprint
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking laravel-shift/blueprint (v2.2.0)
  - Locking laravel-shift/faker-registry (v0.1.0)
  - Locking symfony/yaml (v5.4.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading symfony/yaml (v5.4.3)
  - Downloading laravel-shift/faker-registry (v0.1.0)
  - Downloading laravel-shift/blueprint (v2.2.0)
  - Installing symfony/yaml (v5.4.3): Extracting archive
  - Installing laravel-shift/faker-registry (v0.1.0): Extracting archive
  - Installing laravel-shift/blueprint (v2.2.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: backpack/crud
Discovered Package: backpack/generators
Discovered Package: creativeorange/gravatar
Discovered Package: digitallyhappy/assets
Discovered Package: facade/ignition
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel-shift/blueprint
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prologue/alerts
Package manifest generated successfully.
82 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force
No publishable resources for tag [laravel-assets].
Publishing complete.

I'm fine with 2.2 for now, but I thought I ought to send this info along, in case it helps.

Thanks for an amazing package! I'm very excited to start using it.

**Comment by jasonmccreary** [comment]
You're still running Laravel 8. Blueprint 2.3 and above require Laravel 9. [Use Shift to upgrade Laravel](https://laravelshift.com/upgrade-laravel-8-to-laravel-9) quickly.

**Comment by AMAFsoft** [comment]
Same error after installing on a fresh laravel 9

**Comment by jasonmccreary** [comment]
Sorry, but I am unable to reproduce this error. It's likely you have another dependency conflicting with Blueprint. Composer doesn't always point directly to the conflicting package.

**Comment by AMAFsoft** [comment]
Its a fresh Laravel installation.

However , I've solved this issue by using v2.2.0.
