### ISSUE TITLE
DateRangePicker issue when current date is 31st of any month and maxDate prod equals to current date

### ISSUE THREAD

**Issue by lykke-vashetsin** [laravel-shift/blueprint#561]
- Blueprint Version: 
    "@blueprintjs/core": "^3.51.3",
    "@blueprintjs/datetime": "^3.23.19"
- Platform: both mac and windows

### Issue:
It happens in DateRangePicker control when maxDate={currentDate} and currentDate=31st date of any month (e.g. January, March, May, etc.). you can see on screenshot that maxDate equals current date (it was done on 31st March)..
there are two problems: UI is slightly broken and instead February there is January is displayed
![image](https://user-images.githubusercontent.com/73484382/161258162-2e180dc5-0cd4-4860-997f-eae6056ea44c.png)

**Comment by jasonmccreary** [comment]
This has nothing to do with Blueprint.

**Comment by lykke-vashetsin** [comment]
> This has nothing to do with Blueprint.
what is this then?
https://blueprintjs.com/docs/#datetime/daterangepicker

**Comment by jasonmccreary** [comment]
A completely different library (and language) with the same name. 😉

**Comment by lykke-vashetsin** [comment]
indeed :)
