### ISSUE TITLE
Cannot used tabbed list for `relationships` field

### ISSUE THREAD

**Issue by mallardduck** [laravel-shift/blueprint#566]
I am seeing an issue where a list of relationships gets mashed into a single long relationship.

Looking things over, I found an oddly named variable doing a bool check. That is here:

https://github.com/laravel-shift/blueprint/blob/7291204abd56c3d3071f3c1997b57f98fd8358c4/src/Builder.php#L17

Based on the actual logic being checked I would have expected this variable to be named `$notUsingIndex` instead. Or rather the `=/=` swapped for `===` could allow this to logically resolve to a `usingIndex` variable.

As it stands right now - my `drafts.yaml` doesn't have `indexes:` mentioned anywhere yet this resolves as true. This results in the dash `-` being removed as getting a true value here enables the `$strip_dashes` features of `parse`.

---

Working past that initial issue, by doing a nasty vendor hack/patch, I then subsequently found that the `ModelLexer` isn't prepared for the `relationships` value to already be parsed as an array by Yaml.

It would be great if these YAML lists could be parsed "natively" by the Yaml library instead of requiring they be a single line CSV string.

---

UPDATE: I dug a little more and noticed the indexes feature I hadn't used yet. Seems like this "bug" is unlikely to be solvable based on that aspect of things.

Guess I'll just go back to a single line string.

Feel free to close as `Wont fix` - unless someone more clever and well-slept than myself can find a non-breaking fix.

**Comment by mallardduck** [comment]
I was having two issues ultimately - on odd one with how `.blueprint` cache and `indexes:` work; the other one related to how the Lexer handles relationships.

To clarify the Lexer issue - here's an example of something that's valid yaml:

```yaml
models:
  PackageRelease:
    id
    version: string unique
    timestamps
    relationships:
      hasMany:
        - Thing1
        - Thing2
        - Thing3
```

You get this error though:
```
   TypeError 

  explode(): Argument #2 ($string) must be of type string, array given
```

---

The former issue is a bit more complex to explain - especially as a first time user scanning old commits. One thing I was confused about as I was trying to understand this issue was "why can't I use a Yaml list for relationships" and the excerpt above seemed related.

The variable I highlighted has what I would consider a deceptive name. It's doing a regex for the `indexes:` yaml key and named `usingIndexes` however logic check is actually returning true when it's NOT found. Based on the name alone, I would have expected it to be checking for `=== 1` instead of `!==`.

That variable is what controls how the `parse` method then handles the Yaml before actually parsing it via Symfony Yaml. So the issue I was running into was that this code:

https://github.com/laravel-shift/blueprint/blob/7291204abd56c3d3071f3c1997b57f98fd8358c4/src/Blueprint.php#L41-L43

Is activating and causing what was once a yaml list, to be parsed as a single very long string. So all of the relationships are merged into one result - i.e. using the example above, instead of 3 relationships it generates `Thing1Thing2Thing3` relationship.

**Comment by jasonmccreary** [comment]
@mallardduck, Blueprint uses YAML. But it doesn't necessarily support all the various ways you might structure the data.

In this case, as you found in the docs, relationships are a comma separated string - not an array/list.
