### ISSUE TITLE
Custom name for column of type id

### ISSUE THREAD

**Issue by maurohmartinez** [laravel-shift/blueprint#568]
### Synopsis:
It will be nice to be able to generate a migration with a column of type id and with a custom name. For example:

```
Schema::create('table_name', function (Blueprint $table) {
    $table->id('custom_name_id');
    // or...
    $table->id('id_custom_name');
});
```
For example...
```
models:
  ModelName:
    custom_name_id: id ----> (here I tried primary, key, autoIncrement, etc, but nothing works...)
```
the above generates relationships which are not needed since `custom_name_id` is supposed to be the primary key model and column.

### Proposed Syntax:
-

### Expected Behavior:
-

**Comment by jasonmccreary** [comment]
This behavior exists ([doc reference](https://blueprint.laravelshift.com/docs/keys-and-indexes/#model-keys-indexes)).

Basically, you would write:

```yaml
    custom_name_id: id foreign: custom_model.id
```

**Comment by maurohmartinez** [comment]
@jasonmccreary Thanks for your reply!

Not sure this achieves what I need. Imagine I create a Model named `Car` and I want the migration file for `cars` table to have a primary id defined like this `$table->id('custom_id');` instead of `$table->id();` which also happens to be the primary key for `Car` Model.

When trying your solution `custom_id: id foreign:car.id` I get as a result a migration file like this:

`$table->foreignId('custom_id')->constrained('car');`

And a `Model` file with a relationship:
```
public function custom()
{
    return $this->belongsTo(Car::class);
}
```
and no `$primaryKey` defined in Model: `protected $primaryKey = 'custom_id';`

---
All I need is the migration file with an id define as `$table->id('custom_id');` and the Model with the `protected $primaryKey = 'custom_id';` defined without relationships.

What am I doing wrong?
Thanks!

**Comment by jasonmccreary** [comment]
I believe this is possible within Blueprint. However, it would be helpful if you provided a short YAML definition instead of the final code. This lets me know what you tried.

**Comment by StaffCollab** [comment]
Hi @jasonmccreary 
I have the same problem.
I'm working with a few projects not following conventions and using custom primary id names, but the model created doesn't get the $primaryKey set.
Here is an example
~~~
 ItemMaster:
        item_id: integer primary key
        id: false
~~~
I expected the model to include ` public $primaryKey = 'item_id';` but it is not getting generated (and every time I'm doing `blueprint:build`, it is getting overwritten even if I add it manually).

**Comment by tottello** [comment]
Any news? I would like to use custom name form primary column instead of 'id'

**Comment by jasonmccreary** [comment]
I'm willing to support this. Feel free to open a PR.
