### ISSUE TITLE
Specifying size of integer columns

### ISSUE THREAD

**Issue by mahfoudfx** [laravel-shift/blueprint#572]
- Laravel Version: 9.29.0
- PHP Version: 8.10.0
- Blueprint Version: 2.4.0
- Platform: Mac | Windows | Linux

### Issue:
When using size attribute with any integer blueprint integer (bigInteger, mediumInteger, tinyInteger, smallInteger, etc...), it will generate a Laravel migration format that call SQL to create a Primary Key with Auto Increment. 
Please check this similar generated [Issue](https://stackoverflow.com/questions/28884918/laravel-table-there-can-be-only-one-auto-column-and-it-must-be-defined-as-a-key).

### draft.yaml:
```yaml
code_no: smallInteger:3 unsigned unique
```
will generate
```php
$table->unsignedSmallInteger('code_no', 3)->unique()
```
It maybe more adequate to generate
```php
$table->unsignedSmallInteger('code_no')->length(3)->unique()
```

**Comment by mahfoudfx** [comment]
As stated in the [link](https://stackoverflow.com/questions/28884918/laravel-table-there-can-be-only-one-auto-column-and-it-must-be-defined-as-a-key) of my previous post:
> if you use any integer blueprint (bigInteger, mediumInteger, tinyInteger, smallInteger, etc...) with any second parameter (other than 0) you are telling Laravel to make an integer with an auto_increment property, this will return:
Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key")

So this syntax is Ok for string but not for integers.
I have to admit that when I first investigated the error, I started with my draft file, which was Ok, than I checked migration file, the generated code were as expected, than I have dig deeper and learn that is from Laravel itself.

**Comment by jasonmccreary** [comment]
Gotcha. Feel free to submit a PR with the fix. Otherwise, I will patch this in a [future live stream](https://www.youtube.com/watch?v=xCHi-JswDgI&list=PLmwAMIdrAmK5q0c0JUqzW3u9tb0AqW95w&index=33).

**Comment by faustbrian** [comment]
@jasonmccreary can this be closed based on https://github.com/laravel/framework/issues/1465#issuecomment-18700321?

**Comment by jasonmccreary** [comment]
I think the "fix" here is to ignore any length for all _integer_ columns. Blueprint should not generate code which adds a length parameter or chains `->length()` to any _integer_ column.
