### ISSUE TITLE
Update mail.stub to use new Mailable syntax

### ISSUE THREAD

**Issue by dannyrevenant** [laravel-shift/blueprint#578]
### Synopsis:
In [this PR](https://github.com/laravel/framework/pull/44462), Taylor updated the default syntax for Mailables. This is now the default in laravel core and in the docs.

### Proposed Syntax:
As per the docs/repo, but presumably without the __construct as I think we usually skip that?

### Expected Behavior:
mail.stub is generated with the new syntax

I think this should "just work"

**Comment by jasonmccreary** [comment]
While Blueprint does aim to be the latest, greatest with Laravel features, this might be too fast.

I'm glad to do this after the Laravel X release. But for now, we'll keep the _Mailables_ as they were at the time of Laravel 9's release.

If you want this, you can update your own Mailable stub or submit a PR with a configuration option to use the "new" syntax.
