### ISSUE TITLE
Need ignore softDeletesTz and softDeletes in resources and requests

### ISSUE THREAD

**Issue by FlashWS** [laravel-shift/blueprint#585]
- Laravel Version: 9.14
- PHP Version: 8.1
- Blueprint Version: 2.4
- Platform: Windows

### Issue:
In app/Http/Resources/PostResource.php:
```php
        return [
            'id' => $this->id,
            'title' => $this->title,
            'softdeletestz' => $this->softdeletestz,
        ];
```

In app/Http/Requests/PostStoreRequest.php:
```php
        return [
            'title' => ['required'],
            'softdeletestz' => ['required'],
        ];
```
### draft.yaml:
```yaml
Post:
    title: string:400
    softDeletesTz
```

**Comment by jasonmccreary** [comment]
Thanks. Seems like `softdeletestz` is not ignored when generating these classes. It should be for the form request, I'm not sure about the resource.

Feel free to open a PR. Otherwise, I'll try to get to this early next year.
