### ISSUE TITLE
Generate comment blocks with model relationships 

### ISSUE THREAD

**Issue by striderwhitepderas** [laravel-shift/blueprint#594]
### Synopsis:
It would be nice if blueprint generated relationships with a comment block/header. At minimum where it stipulated its return type. 

### Proposed Syntax:
For example, stipulate the return type in the comment header

```php
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function clips()
    {
        return $this->hasMany(Clip::class);
    }
```

**Comment by jasonmccreary** [comment]
Does this not happen if you enable the DocBlock comments within the configuration?

**Comment by jasonmccreary** [comment]
Closing as the new default behavior is to add the return type hint.
