### ISSUE TITLE
Error installing version 2.6.0

### ISSUE THREAD

**Issue by sajaddp** [laravel-shift/blueprint#599]
Thanks for the recent update.
I encountered the following error while installing version 2.6.0.
I got Laravel and immediately installed the package!

- Laravel Version: 10.1.5
- PHP Version: 8.2.3
- Blueprint Version: 2.6.0
- Platform: Mac

### Issue:

```
- laravel-shift/blueprint v2.6.0 requires symfony/yaml ^6.3 -> found symfony/yaml[6.3.x-dev] but it does not match your minimum-stability.
```

**Comment by jasonmccreary** [comment]
Looks like the wrong constraint. Please point to `dev-master` and let me know if that fixes it.

**Comment by sajaddp** [comment]
@jasonmccreary 
I tested it and it was installed correctly.

```
composer require --dev laravel-shift/blueprint:dev-master
```
