### ISSUE TITLE
Draft file could not be found: [draft

### ISSUE THREAD

**Issue by KapilBagdi** [laravel-shift/blueprint#601]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Blueprint Version: #.#.#
- Platform: Mac | Windows | Linux

### draft.yaml:
```yaml
# PLEASE PASTE THE DRAFT FILE WHICH REPRODUCES THE ISSUE HERE...
```

**Comment by faustbrian** [comment]
@KapilBagdi is there a repository for reproduction?

**Comment by faustbrian** [comment]
@jasonmccreary can this be closed since there is no useful info here?
