### ISSUE TITLE
Generate Laravel Nova Resources

### ISSUE THREAD

**Issue by faustbrian** [laravel-shift/blueprint#626]
### Synopsis:

Having Nova resource classes generated out of the box would be handy, even if opt-in. I know there's https://github.com/Naoray/blueprint-nova-addon but Laravel Nova is a popular first-class package so it would be nice to have out of the box support for it.

### Proposed Syntax:

No additional syntax needed. This would be done based on models.

### Expected Behavior:

Generate resource classes for Laravel Nova.

**Comment by jasonmccreary** [comment]
With respect to Nova, there is already a community add-on for this.
