### ISSUE TITLE
User::id or just "id" naming Relationsships in yaml file breaks generation of files

### ISSUE THREAD

**Issue by nsoncode** [laravel-shift/blueprint#63]
Error message:"  BadMethodCallException  : Method Illuminate\Support\Str::beforeLast does not exist."

in yaml refering to user id in relation for instance:

user_id   <-- works
user::id   <-- Do not work
id            <-- Do not work

version 1.2.1

Thank for your efforts! keep it up!

**Comment by jasonmccreary** [comment]
Blueprint requires the latest version of Laravel 6.
