### ISSUE TITLE
String interpolation ${} in PHP8.2 warning

### ISSUE THREAD

**Issue by impeto** [laravel-shift/blueprint#648]
- Laravel Version: 10.32.1
- PHP Version: 8.2.12
- Blueprint Version: 2.7.0
- Platform: Mac (actually Linux on Docker, Laravel Sail)

### Issue:
Running `blueprint:new` (and probably other blueprint commands) in PHP 8.2 gives this warning. The yaml file was created, but I switched to 8.1 so I didn't have to deal with it.

```
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php on line 525
```

~inpeto

**Comment by jasonmccreary** [comment]
Can you open a PR with the fix?

**Comment by impeto** [comment]
Just did PR #649
