### ISSUE TITLE
Failed Installing on newest Laravel

### ISSUE THREAD

**Issue by mai92** [laravel-shift/blueprint#654]
![Screenshot 2023-12-04 at 11 44 00](https://github.com/laravel-shift/blueprint/assets/12948227/1268b0e6-804b-45eb-a7d5-5aa63111a9f9)

- Laravel Version: 10.34.2 
- PHP Version: 8.2.2
- Blueprint Version: latest
- Platform: Mac | Windows

### Issue:

Installation Failed

**Comment by mai92** [comment]
> You haven't included the command you ran to install Blueprint, but my guess would be appending `-W` will solve your issue.

`composer require --dev laravel-shift/blueprint` just used command on documention page, 

yes after appending `-W` its solved the issues, thank you @jasonmccreary

**Comment by Patapoof** [comment]
Thanks for correcting the README.md to mention the -W flag, but there is another documentation which isn't updated, the one the majority of users will use, because Google:
https://blueprint.laravelshift.com/docs/installation/
