### ISSUE TITLE
error about HttpTestAssertions

### ISSUE THREAD

**Issue by mgamal92** [laravel-shift/blueprint#66]
please include `jasonmccreary/laravel-test-assertions` package in composer.json of this package because it gives me an error

**Comment by jasonmccreary** [comment]
It's probably best if you add it yourself, that way if you ever remove the `laravel-shift/blueprint` dependency (or make it global) the project still has it.

However, I will throw it in the suggests.

**Comment by jasonmccreary** [comment]
The [jasonmccreary/laravel-test-assertions](https://github.com/jasonmccreary/laravel-test-assertions) has been added to Composer's package suggestions in v1.3.1.

We'll see how that goes for now. If necessary, I'll have Blueprint check for it on the first run.
