### ISSUE TITLE
Add in already on going project

### ISSUE THREAD

**Issue by MasterAdmin2** [laravel-shift/blueprint#660]
### Synopsis:
Sir, I was working on a project, and it's my big project as of my own, So, what I was doing till today is doing models and migrations manually one by one, and I found your potent yet elegant tool in Laracast. But my application is in mid-stage and there is no way to generate a draft YAML from scratch for me,

### Proposed Syntax:
so what I want is if the project is in the ongoing stage or anyone adds this tool in a later phase then there should be a command by which a draft like YAML script should be generated so that he can continue with your tool afterward. 

### Expected Behavior:

any command which helps me to generate a YAML-like file so that it will be easy for me as well to understand and continue working

But Seriously hats off to the Developer of this tool, its blazing fast as well as too smooth like creating things just like magic without touching any file.

**Comment by jasonmccreary** [comment]
I don't really understand the request. However, Blueprint can definitely be used on existing projects. You should look into the `trace` command. It will scan your current models so you may easily reference them in relationships or controllers.

**Comment by MasterAdmin2** [comment]
sir, my requirement is
I was looking at the draft.yaml file and it was blank when I installed your module in my existing code. so in clear words, I am asking if is it possible that when I add your module inside my existing project it will automatically fetch all things in draft file or any other file in same format just like we define inside draft file to make all migrations and all things.

**Comment by jasonmccreary** [comment]
No, Blueprint does not create a draft file for an existing application. It's a _passive generator_. Its direction is 1-way.

**Comment by MasterAdmin2** [comment]
> No, Blueprint does not create a draft file for an existing application. It's a _passive generator_. Its direction is 1-way.

thanks for the update sir, can I ask you one more question if possible related to laravel filament, if you can help in your spare time, just a simple question for an elite developer like you.
