### ISSUE TITLE
Plural route naming convention as default to match Laravel docs

### ISSUE THREAD

**Issue by bertheyman** [laravel-shift/blueprint#662]
### Synopsis:
[This debate](https://github.com/laravel-shift/blueprint/issues/480) and [subsequent PR](https://github.com/laravel-shift/blueprint/pull/574/files) allowed for routes names to be configurable: singular or plural.

The Blueprint default differs from the Laravel docs:

Blueprint
```php
Route::resource('photo', PhotoController::class);
```

Laravel docs
```php
Route::resource('photos', PhotoController::class);
```

### Proposed Syntax:

```php

// config/blueprint.php

'singular_routes' => null,
```

### Expected Behavior:

Have plural as the default option to match the docs and promote Laravel conventions.
I realise there is no 100% official naming conventions, but I believe sticking to the docs will help promote one standard.

**Comment by jasonmccreary** [comment]
I agree that the plural/singular is a bit off. If you want to open a PR to correct some of this, I am glad to revisit it.
