### ISSUE TITLE
request to add indexes example on the docs

### ISSUE THREAD

**Issue by besingamkb** [laravel-shift/blueprint#671]
### Synopsis:
I found it hard to find example on how to create indexes from the docs. I just figure it out after searching to the github issue and found this comment https://github.com/laravel-shift/blueprint/issues/271#issuecomment-647009889

**Comment by jasonmccreary** [comment]
Feel free to open a PR with an example to the [docs repo](https://github.com/laravel-shift/blueprint-docs).
