### ISSUE TITLE
Split faker generation to registry package

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#7]
The translation used by Blueprint is also used by the Model Factory Generator. I envision other packages benefiting from this data and as such would like to separate it to its own package and include it as a dependency.

**Comment by Naoray** [comment]
Maybe this could help you find some ideas:
To guess faker method based on name, type or nativeFakerMethods I've created a [TypeGuesser](https://github.com/Naoray/laravel-factory-prefill/blob/master/src/TypeGuesser.php) class in my factory-prefill pkg which is derived from [Faker's own Name Guesser](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Guesser/Name.php).

**Comment by jasonmccreary** [comment]
Thanks. I'll check it out.

**Comment by jasonmccreary** [comment]
@Naoray, finally circling back to this. I [created a separate package](https://github.com/laravel-shift/faker-registry.git) to serve as a registry for generating Faker data. It's pretty basic right now, just for Blueprint's needs.

However, would love to work together to improve it as I think lots of packages could benefit from a shared registry. Also easier for developers to contribute to and keep up-to-date in isolation.

cc: @christophrumpel

**Comment by Naoray** [comment]
@jasonmccreary cool! Will check it out in the coming week.

Would love to work on the package with you and @christophrumpel together!

**Comment by jasonmccreary** [comment]
Awesome. We'll see what Chrisoph thinks. Maybe we could all jump on a quick call sometime to see how to improve it. Glad to open PRs in the projects to begin sharing.

**Comment by christophrumpel** [comment]
Hey, sry guys couldn't check so far. Currently on holidays 🏔:-) A call would be nice 👍
