### ISSUE TITLE
Invalid return type produced by the ControllerGenerator

### ISSUE THREAD

**Issue by yolcuiskender** [laravel-shift/blueprint#705]
- Laravel Version: v11.30.0
- PHP Version: PHP 8.3.1
- Blueprint Version: 2.10
- Platform: Windows

For the sake of the example, I am ignoring #703.

### Issue:
Produced controller does have wrong return type.
Current test coverage does not catch the issue correctly and **produces false negatives**.

![image](https://github.com/user-attachments/assets/02856e6a-9c61-43a0-88fc-7000ea64e84c)

The actual test code relies too heavily on mocks rather than testing the actual functionality of the library itself. I didn't see any test that covers `buildMethods` but then again I didn't do a thorough deep dive either, maybe I have missed it.

The issue seems to be related in the improper handling of line endings mixed with inconsistent line endings within the stub files when importing the library using composer. When you clone the repo you get `0x0D` and `0x0A` **together** in the stub files but if you require the library into an existing project, **you only seem to get** `0x0A`.

Nevertheless, the code actually runs faster and more reliable if you don't use PHP_EOL as it is unrelated at this point since the produced code only requires changes at the function signature which isn't really multiline so PHP_EOL is a bit overkill here.

### draft.yaml:
```yaml
models:
  Library:
    id: uuid
    name: string
    description: string
    created_at: datetime
    updated_at: datetime

controllers:
  LibraryController:
    resource: api.store
```

#704 actually solves both issues of #703 and #705.

These are my observations, I hope it helps.

**Comment by jasonmccreary** [comment]
Sorry, I'm not following the issues here. While I appreciate to contribution, I did ask in a PR if you could keep the changes isolated so it's easier to understand.

**Comment by yolcuiskender** [comment]
**Here are the step by step instructions on how to re-produce the error:**

1. Install new laravel app
`laravel new blank-app`

2. Install blueprint
`composer require -W --dev laravel-shift/blueprint jasonmccreary/laravel-test-assertions`

3. Create draft file:
```yaml
models:
  Library:
    id: uuid
    name: string
    description: string
    created_at: datetime
    updated_at: datetime

controllers:
  LibraryController:
    resource: api.store
```

4. Generate code with blueprint
`php artisan blueprint:build`

5. Produced code:
```php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LibraryStoreRequest;
use App\Http\Resources\LibraryResource;
use App\Models\Library;
use Illuminate\Http\Request;

class LibraryController extends Controller
{
    public function store(LibraryStoreRequest $request): Response
    {
        $library = Library::create($request->validated());

        return new LibraryResource($library);
    }
}
```

The correct signature would be:
```PHP
public function store(LibraryStoreRequest $request): LibraryResource
```

**Reason this is happening:**
Line endings in the generated code are \n only but blueprint is using PHP_EOL which looks for \r\n and can not find the function signature it tries to replace the return type for.



The image shows the characters at the end of the stub file [vendor/laravel-shift/blueprint/stubs/controller.method.stub](https://github.com/laravel-shift/blueprint/blob/master/stubs/controller.method.stub)
![image](https://github.com/user-attachments/assets/9e743790-bd89-4e0a-9395-127dc6a4c835)

I've put a breakpoint on line 196 in [vendor/laravel-shift/blueprint/src/Generators/ControllerGenerator.php](https://github.com/laravel-shift/blueprint/blob/master/src/Generators/ControllerGenerator.php).
![image](https://github.com/user-attachments/assets/b64948dd-3a35-410e-b477-2efc17f2d6aa)

The generated code does have \n endings but the str_replace function is searching for a string that has PHP_EOL which is \r\n in this case:
![image](https://github.com/user-attachments/assets/c64ba94a-3b27-469f-a19e-e94583a364fa)

Therefore the produced method is not replaced with the correct return type:
![image](https://github.com/user-attachments/assets/3aee3529-9f2b-4e3c-8340-019d0aa02bbd)

In this case, the PHP_EOL isn't really needed in the search string as the function signature consists only of a single line.
The code works if the PHP_EOL is removed from the search string.

`PHP $method = str_replace('): Response' . PHP_EOL, '): ' . Str::afterLast($returnType, '\\') . PHP_EOL, $method);`
`PHP $method = str_replace('): Response', '): ' . Str::afterLast($returnType, '\\'), $method);`

Regardless of this, if I clone the repo blueprint to work on it, the stub files suddenly have \r\n endings.
![image](https://github.com/user-attachments/assets/438e24e7-3b65-48d0-8104-780357a605c3)

The behaviour is weird, maybe related to how composer handles files or maybe something else however I don't think any test will solve this in the current situation as it will have different data from the fixtures in the UUT and the production environment.

**Comment by yolcuiskender** [comment]
This issue is still relevant as it prevents the library from functioning correctly. I don't know if it is Windows specific.
