### ISSUE TITLE
jasonmccreary/laravel-test-assertions is not automatically included

### ISSUE THREAD

**Issue by peterjaap** [laravel-shift/blueprint#71]
When running `php artisan test` it complains about not having `jasonmccreary/laravel-test-assertions`:

```
php artisan test             
PHP Fatal error:  Trait 'JMac\Testing\Traits\HttpTestAssertions' not found
```

**Comment by jasonmccreary** [comment]
My guess is you don't have the dependency installed for whatever project you're using with Blueprint.

Running the following command should resolve the issue:

```sh
composer require --dev jasonmccreary/laravel-test-assertions
```

Blueprint itself doesn't require this as it may already be a project dependency. However, I may add it to the _suggested_ packages if anyone else runs into this issue.

**Comment by peterjaap** [comment]
@jasonmccreary yeah I figured that out, I think adding it to the suggested part of composer is a good idea :+1:
