### ISSUE TITLE
Creating malformed migrations.

### ISSUE THREAD

**Issue by mwwhitted** [laravel-shift/blueprint#713]
- Laravel Version: 11.35.0
- PHP Version: 8.3.14
- Blueprint Version: 2.10
- Platform: Mac

### draft.yaml:
models:
  Category:
    name: string
    description: text
    relationships:
      hasMany: Products

  Product:
    category_id: foreignId:categories
    brand_id: foreignId:brands
    supplier_id: foreignId:suppliers
    name: string
    description: text
    sku: string:unique
    price: decimal:10,2
    weight: decimal:8,2
    dimensions: string
    material: string
    image_url: string
    relationships:
      hasMany: Suppliers
      belongsTo: Category

  Brand:
    product_id: foreignId:products
    name: string
    website_url: string
    relationships:
      hasMany: Products

  ProductBrand: # Pivot Table
    product_id: foreignId:products
    brand_id: foreignId:brands

  Stock:
    product_id: foreignId:products
    quantity_available: integer
    reorder_threshold: integer
    relationships:
      belongsTo: Product

  Fitment:
    product_id: foreignId:products
    compatible_with: string
    relationships:
      belongsTo: Product

  Supplier:
    product_id: foreignId:products
    name: string
    contact_info: text
    website_url: string
    relationships:
      hasMany: Products

  ProductSupplier: # Pivot Table
    product_id: foreignId:products
    supplier_id: foreignId:suppliers
    supplier_price: decimal:10,2

  Customer:
    name: string
    email: string:unique
    phone: string:nullable
    address: text

  Order:
    customer_id: foreignId:customers
    order_date: timestamp
    status: enum:pending,shipped,canceled
    relationships:
      hasMany: OrderItems
      belongsTo: Customer

  OrderItem:
    order_id: foreignId:orders
    product_id: foreignId:products
    quantity: integer
    price_at_purchase: decimal:10,2
    relationships:
      belongsTo: Order

relations:
  ProductBrand:
    belongsTo: Product, Brand

  OrderOrderItem:
    belongsTo: Order, OrderItem

  ProductSupplier:
    belongsTo: Product, Supplier

seeders: Brand,
  Category,
  Customer,
  Fitment,
  Order,
  OrderItem,
  Product,
  Stock,
  Supplier,
  ProductBrand,
  ProductSupplier

**Comment by jasonmccreary** [comment]
`unique` is a _modifier_. You're writing it as an _attribute_ of `string`. [Review the docs](https://blueprint.laravelshift.com/docs/model-data-types/) for more detail, but here's the corrected YAML:

```yaml
sku: string unique
```

**Comment by mwwhitted** [comment]
Jason,

Thanks for your lightning fast response!

Sorry. I am brand new at Laravel and Blueprint. I will review the docs.

Thanks!
Mark

Mark Whitted
***@***.***
‪817.504.5702	‬ 


￼
