### ISSUE TITLE
Allow `uuid` shorthand and automatic primary key

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#77]
While `uuid` column types are support, they are currently a bit verbose to define.

It would be nice instead of the current definition of `id: uuid primary`, to be able to simply use a shorthand of `uuid` that would expand to `id: uuid`

This implies the use of the `primary` _modifier_ if a user were to define `id: uuid`.

**Comment by jasonmccreary** [comment]
I think @ttomdewit mentioned taking a stab at this. If not, I'll work on it during the next live-stream.

**Comment by ttomdewit** [comment]
I was hoping to do it last night but unfortunately had to finish some other work. Can’t see myself finishing it within the next 8 hours or so before your livestream but if I do I’ll make sure to ping you.
