### ISSUE TITLE
Exclude `nullable` columns from model factories

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#78]
In retrospect filling fake data for `nullable` columns seems to be too explicit. Often these columns should be left undefined in the default factory and instead defined in a [factory state](https://laravel.com/docs/5.8/database-testing#factory-states).

This is open for discussion as it would be a _breaking change_ based on original behavior.

**Comment by Naoray** [comment]
Why don't we add a setting is set to allow `nullables` by default to prevent a breaking change?

```php
'factory_fill_nullable' => true,
```

Then we just need to check if the setting is set to `false` and if so filter the `$models->columns()` based on the `nullable` modifier.

**Comment by jasonmccreary** [comment]
Yeah. That's fair. Maybe in `2.0`, I'll change this to `false`.

The more I test, the more I don't like the nullable columns to be filled as it forces me to explicit set these in my test case or, better yet, add a [factory state](https://laravel.com/docs/7.x/database-testing#factory-states).

**Comment by Naoray** [comment]
:+1: will give it a try tomorrow morning

**Comment by Naoray** [comment]
was easier than expected :smile:
