### ISSUE TITLE
Erase command error and rerun

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#82]
The erase command has two bugs:

1. It errors when previous models were created
2. After running, it still stores the previously _built_ files

**Comment by empirefx** [comment]
The plural function may cause this?

https://github.com/laravel-shift/blueprint/blob/4dd672a3da461cfe0abb00c31344d28f9fd5218d/src/Models/Model.php#L93

Without it my migrations have the proper table name.
Never used Inflector from Doctrine, tinker
```Psy Shell v0.10.3 (PHP 7.3.17-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> use Doctrine\Common\Inflector\Inflector;
>>> $plural = Inflector::pluralize('People');
=> "People"
>>> $plural = Inflector::pluralize('Person');
=> "People"
>>> $plural = Inflector::pluralize('Browser');
=> "Browsers" ```

**Comment by jasonmccreary** [comment]
What?

**Comment by jasonmccreary** [comment]
These seems to mostly be resolved by recent works. However, `erase` no calls `trace` to ensure the cached models are correct.

As an aside, this is not a command I want to spend a lot of time on and in the future may be removed. I provided it for symmetry and convenience.

However, using version control is always going to be the better solution.

For example, in Git:
- Run `blueprint:build` from a _clean working state_ (i.e. nothing in the index when running `git status`
- Instead of erase, run `git reset --hard`
