### ISSUE TITLE
Migration - Duplication unless erased.

### ISSUE THREAD

**Issue by MattHadfield113** [laravel-shift/blueprint#90]
If we use Blueprint to create migrations, then change something and re-run, it will recreate all the migrations unless we clear them.

Might be worth logging what exactly has been created, including file names and the content of each file, then checking the contents of the migrations and seeing if they match to stop it creating everything allover again without having to use the erase command.

Example -

I create my app, start modifying, and then decide to add a new column, by running build again it will create every migration again, rather than updating the existing already there migrations, but if i erase, i will lose any changes that i have already made.

Im aware we could just create another custom migration to add the new column, however i feel this would be a nice feature to have in blueprint.

**Comment by jasonmccreary** [comment]
Definitely a nice to have, but not very easy to achieve. Blueprint does not "track your changes".

Furthermore, Blueprint is all about speed. That goes both ways. In this case, it's probably faster to simply add the column to the existing migration.

I welcome any PRs or suggested implementations. Maybe there's opportunity for a separate command, such as `redraft` or `amend`.
