### ISSUE TITLE
Default text cant have a space between words

### ISSUE THREAD

**Issue by MattHadfield113** [laravel-shift/blueprint#91]
```
  BillingProfile:
    invoice_country: string default:"United Kingdom"
```

With the space inbetween the two, it gets to "United but then skips as it sees a space.

```
        Schema::create('billing_profiles', function (Blueprint $table) {
            $table->string('invoice_country')->default("United);
        });
```

I have tried this with both Single and Double quotes to the same effect.

**Comment by jasonmccreary** [comment]
This one is a legit bug. I think the `ModelLexer` simply splits on spaces for some of the modifiers.

Feel free to open a PR. If not, I should have a patch early next week.

**Comment by MattHadfield113** [comment]
Only just seen this reply as ive been a little stacked.

Not that good at testing yet (On my todolist for learning) so will leave this one in your capable hands @jasonmccreary !

**Comment by jasonmccreary** [comment]
@MattHadfield113 no worries. Will do.

Check out [Confident Laravel](https://confidentlaravel.com/) when you have more time ;)
