### ISSUE TITLE
Symfony Yaml Parser not working for me

### ISSUE THREAD

**Issue by adevade** [laravel-shift/blueprint#95]
Hello!

I pulled down the project and wanted to work on some PRs tonight, but it doesn't want to work! 😞 
It seems to be something with Symfony's Yaml parser, but I can't find what's wrong! It's parsing the input wrong. 

```diff
There was 1 failure:

1) Tests\Feature\BlueprintTest::it_parses_shorthands
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'models' => Array (
-        'Name' => Array (...)
+        'Name' => 'softDeletes id timestamps'
     )
     'controllers' => Array (
-        'Context' => Array (...)
+        'Context' => 'resource'
     )
 )

blueprint/tests/Feature/BlueprintTest.php:95
```

Totally I get over 50 errors and failures on a clean install from master. 
Am I supposed to be running this from within a Laravel project? I'm assuming I'm doing something wrong, but I would appreciate any help figuring this out!

```
ERRORS!
Tests: 197, Assertions: 903, Errors: 49, Failures: 3.
```

OS: Windows 10
PHP: 7.3.16
PHPUnit: 9.0.1

**Comment by jasonmccreary** [comment]
The tests don't have to be run from within a Laravel project. But the actual commands should be run from within a Laravel project.

**Comment by adevade** [comment]
**Found the error!** Putting this here for future Windows users:

Make sure your Git client is set on using `lf` line endings when fetching repos. Everything breaks with Windows default `crlf` line endings.

I ran the following commands, and now it's working.

```
git config --global core.autocrlf false
git config --global core.eol lf
```

Only use --global if you know what you're doing!

**Comment by adevade** [comment]
I think it's easily fixable by adding this line to the beginning of the Blueprint parser: 

Blueprint.php@parse : 29
```php
$content = str_replace("\r\n", "\n", $content);
```
